// src/words.js

export const UNITS_DATA = [
  { id: "1", name: "יחידה 1: מילות קישור, זמן ומיקום" },
  { id: "2", name: "יחידה 2: אוצר מילים כללי ופעלים מרכזיים" },
  { id: "3", name: "יחידה 3: אוצר מילים מתקדמת ואקדמית" },
  { id: "4", name: "יחידה 4: אוצר מילים מורחב וביטויים נפוצים" }
];

export const WORDS_DATA = {
  "1": [
    { id: "1_1", english: "10th - tenth", hebrew: "עשירי" },
    { id: "1_2", english: "1st - first", hebrew: "ראשון" },
    { id: "1_3", english: "2nd - second", hebrew: "שני" },
    { id: "1_4", english: "3rd - third", hebrew: "שלישי" },
    { id: "1_5", english: "4th - fourth", hebrew: "רביעי" },
    { id: "1_6", english: "5th - fifth", hebrew: "חמישי" },
    { id: "1_7", english: "6th - sixth", hebrew: "שישי" },
    { id: "1_8", english: "7th - seventh", hebrew: "שביעי" },
    { id: "1_9", english: "8th - eighth", hebrew: "שמיני" },
    { id: "1_10", english: "9th - ninth", hebrew: "תשיעי" },
    { id: "1_11", english: "about", hebrew: "אודות / על" },
    { id: "1_12", english: "about", hebrew: "בערך / סביב" },
    { id: "1_13", english: "above", hebrew: "מעל" },
    { id: "1_14", english: "above all", hebrew: "מעל הכל / בראש ובראשונה" },
    { id: "1_15", english: "absolutely", hebrew: "לחלוטין / בהחלט" },
    { id: "1_16", english: "according", hebrew: "לפי / בהתאם ל-" },
    { id: "1_17", english: "accordingly", hebrew: "בהתאם לכך" },
    { id: "1_18", english: "across", hebrew: "מעבר ל- / ברחבי" },
    { id: "1_19", english: "additionally", hebrew: "בנוסף לכך" },
    { id: "1_20", english: "adjacent to", hebrew: "סמוך ל- / ליד" },
    { id: "1_21", english: "after", hebrew: "אחרי / לאחר" },
    { id: "1_22", english: "after all", hebrew: "אחרי הכל" },
    { id: "1_23", english: "after all", hebrew: "למרות הכל" },
    { id: "1_24", english: "afterwards", hebrew: "לאחר מכן" },
    { id: "1_25", english: "again", hebrew: "שוב" },
    { id: "1_26", english: "against", hebrew: "נגד / כנגד" },
    { id: "1_27", english: "ahead of", hebrew: "לפני (בזמן/מקום)" },
    { id: "1_28", english: "albeit", hebrew: "אם כי / אף על פי ש-" },
    { id: "1_29", english: "all in all", hebrew: "בסך הכל" },
    { id: "1_30", english: "along", hebrew: "לאורך" },
    { id: "1_31", english: "along with", hebrew: "יחד עם" },
    { id: "1_32", english: "alongside", hebrew: "לצד / במקביל" },
    { id: "1_33", english: "also", hebrew: "גם / בנוסף" },
    { id: "1_34", english: "although", hebrew: "למרות ש-" },
    { id: "1_35", english: "altogether", hebrew: "לגמרי / בסך הכל" },
    { id: "1_36", english: "always", hebrew: "תמיד" },
    { id: "1_37", english: "amid", hebrew: "בקרב / בתוך" },
    { id: "1_38", english: "among", hebrew: "בין (רבים) / בקרב" },
    { id: "1_39", english: "and", hebrew: "ו- / וגם" },
    { id: "1_40", english: "around", hebrew: "מסביב / בערך" },
    { id: "1_41", english: "as", hebrew: "כמו / בתור" },
    { id: "1_42", english: "as", hebrew: "מכיוון ש- / כש-" },
    { id: "1_43", english: "as a result", hebrew: "כתוצאה מכך" },
    { id: "1_44", english: "as if", hebrew: "כאילו" },
    { id: "1_45", english: "as long as", hebrew: "כל עוד" },
    { id: "1_46", english: "as soon as", hebrew: "ברגע ש- / בהקדם" },
    { id: "1_47", english: "as well as", hebrew: "כמו גם / בנוסף ל-" },
    { id: "1_48", english: "aside from", hebrew: "מלבד / חוץ מ-" },
    { id: "1_49", english: "at", hebrew: "ב- / אצל / בתוך" },
    { id: "1_50", english: "at first", hebrew: "בהתחלה" },
    { id: "1_51", english: "at last", hebrew: "לבסוף" },
    { id: "1_52", english: "backward", hebrew: "אחורה / לאחור" },
    { id: "1_53", english: "based on", hebrew: "מבוסס על" },
    { id: "1_54", english: "because", hebrew: "בגלל ש- / כי" },
    { id: "1_55", english: "because of", hebrew: "בגלל / בעקבות" },
    { id: "1_56", english: "before", hebrew: "לפני" },
    { id: "1_57", english: "before", hebrew: "בטרם" },
    { id: "1_58", english: "behind", hebrew: "מאחורי" },
    { id: "1_59", english: "being that", hebrew: "היות ש- / מכיוון ש-" },
    { id: "1_60", english: "below", hebrew: "מתחת" },
    { id: "1_61", english: "beneath", hebrew: "מתחת ל- / למטה מ-" },
    { id: "1_62", english: "beside", hebrew: "לצד / על יד" },
    { id: "1_63", english: "besides", hebrew: "חוץ מזה / מלבד" },
    { id: "1_64", english: "besides", hebrew: "בנוסף ל-" },
    { id: "1_65", english: "besides", hebrew: "יתר על כן" },
    { id: "1_66", english: "between", hebrew: "בין (שניים)" },
    { id: "1_67", english: "beyond", hebrew: "מעבר ל-" },
    { id: "1_68", english: "both", hebrew: "שניהם / שתי-" },
    { id: "1_69", english: "both... and…", hebrew: "גם... וגם..." },
    { id: "1_70", english: "but", hebrew: "אבל" },
    { id: "1_71", english: "but", hebrew: "אלא / פרט ל-" },
    { id: "1_72", english: "by", hebrew: "על ידי / באמצעות" },
    { id: "1_73", english: "by", hebrew: "עד (זמן) / ליד" },
    { id: "1_74", english: "certainly", hebrew: "בוודאות / בהחלט" },
    { id: "1_75", english: "chiefly", hebrew: "בעיקר" },
    { id: "1_76", english: "close", hebrew: "קרוב / סמוך" },
    { id: "1_77", english: "comparatively", hebrew: "באופן יחסי" },
    { id: "1_78", english: "consequently", hebrew: "כתוצאה מכך" },
    { id: "1_79", english: "consistently", hebrew: "בעקביות / באופן עקבי" },
    { id: "1_80", english: "constantly", hebrew: "כל הזמן / בתמידות" },
    { id: "1_81", english: "contradictory", hebrew: "סותר / נוגד" },
    { id: "1_82", english: "contrary", hebrew: "מנוגד / ההפך" },
    { id: "1_83", english: "conversely", hebrew: "להפך / מאידך גיסא" },
    { id: "1_84", english: "correspondingly", hebrew: "בהתאמה" },
    { id: "1_85", english: "coupled with", hebrew: "בשילוב עם" },
    { id: "1_86", english: "currently", hebrew: "כעת / כרגע" },
    { id: "1_87", english: "daily", hebrew: "יומי / מדי יום" },
    { id: "1_88", english: "despite", hebrew: "למרות / על אף" },
    { id: "1_89", english: "different from", hebrew: "שונה מ-" },
    { id: "1_90", english: "distant", hebrew: "רחוק" },
    { id: "1_91", english: "down", hebrew: "למטה" },
    { id: "1_92", english: "due to", hebrew: "עקב / בגלל" },
    { id: "1_93", english: "during", hebrew: "במהלך / במשך" },
    { id: "1_94", english: "e.g.", hebrew: "לדוגמה (למשל)" },
    { id: "1_95", english: "earlier", hebrew: "מוקדם יותר" },
    { id: "1_96", english: "either... or…", hebrew: "או... או..." },
    { id: "1_97", english: "elsewhere", hebrew: "במקום אחר" },
    { id: "1_98", english: "equally", hebrew: "במידה שווה" },
    { id: "1_99", english: "especially", hebrew: "במיוחד" },
    { id: "1_100", english: "essentially", hebrew: "בעיקרו של דבר / ביסודו" },
    { id: "1_101", english: "even if", hebrew: "אפילו אם" },
    { id: "1_102", english: "even so", hebrew: "אף על פי כן / למרות זאת" },
    { id: "1_103", english: "even though", hebrew: "אף על פי ש- / למרות ש-" },
    { id: "1_104", english: "eventually", hebrew: "בסופו של דבר" },
    { id: "1_105", english: "every day", hebrew: "כל יום" },
    { id: "1_106", english: "every now and then", hebrew: "מדי פעם" },
    { id: "1_107", english: "except", hebrew: "חוץ מ- / פרט ל-" },
    { id: "1_108", english: "farther", hebrew: "רחוק יותר (פיזית)" },
    { id: "1_109", english: "finally", hebrew: "לבסוף" },
    { id: "1_110", english: "first of all", hebrew: "קודם כל / ראשית" },
    { id: "1_111", english: "for", hebrew: "בשביל / עבור" },
    { id: "1_112", english: "for", hebrew: "כי / מכיוון ש- / במשך (זמן)" },
    { id: "1_113", english: "for example", hebrew: "לדוגמה" },
    { id: "1_114", english: "for instance", hebrew: "למשל" },
    { id: "1_115", english: "for the most part", hebrew: "לרוב / בדרך כלל" },
    { id: "1_116", english: "forever", hebrew: "לתמיד / לעד" },
    { id: "1_117", english: "former", hebrew: "קודם / לשעבר" },
    { id: "1_118", english: "forward", hebrew: "קדימה" },
    { id: "1_119", english: "frequently", hebrew: "לעיתים קרובות" },
    { id: "1_120", english: "from", hebrew: "מ- / מתוך" },
    { id: "1_121", english: "from", hebrew: "מאת" },
    { id: "1_122", english: "from time to time", hebrew: "מדי פעם" },
    { id: "1_123", english: "further", hebrew: "הלאה / עוד" },
    { id: "1_124", english: "further", hebrew: "נוסך / מעבר לכך" },
    { id: "1_125", english: "furthermore", hebrew: "יתרה מכך / זאת ועוד" },
    { id: "1_126", english: "given that", hebrew: "בהתחשב בכך ש-" },
    { id: "1_127", english: "granted (that)", hebrew: "אמנם / בהנחה ש-" },
    { id: "1_128", english: "hardly ever", hebrew: "כמעט אף פעם לא" },
    { id: "1_129", english: "hence", hebrew: "לפיכך / משום כך" },
    { id: "1_130", english: "here", hebrew: "כאן / פה" },
    { id: "1_131", english: "how", hebrew: "איך / כיצד" },
    { id: "1_132", english: "however", hebrew: "אולם / יחד עם זאת" },
    { id: "1_133", english: "however", hebrew: "בכל דרך ש-" },
    { id: "1_134", english: "i.e.", hebrew: "כלומר / דהיינו" },
    { id: "1_135", english: "identically", hebrew: "באופן זהה" },
    { id: "1_136", english: "If", hebrew: "אם" },
    { id: "1_137", english: "immediately", hebrew: "מיד / באופן מיידי" },
    { id: "1_138", english: "in", hebrew: "ב- / בתוך" },
    { id: "1_139", english: "in a moment", hebrew: "בעוד רגע / מיד" },
    { id: "1_140", english: "in a word", hebrew: "במילה אחת" },
    { id: "1_141", english: "in addition", hebrew: "בנוסף / יתר על כן" },
    { id: "1_142", english: "in case", hebrew: "במקרה ש- / למקרה ש-" },
    { id: "1_143", english: "in comparison", hebrew: "בהשוואה" },
    { id: "1_144", english: "in conclusion", hebrew: "לסיכום" },
    { id: "1_145", english: "in contrast to", hebrew: "בניגוד ל-" },
    { id: "1_146", english: "in due time", hebrew: "בבוא הזמן" },
    { id: "1_147", english: "in fact", hebrew: "למעשה" },
    { id: "1_148", english: "in fact", hebrew: "בעצם" },
    { id: "1_149", english: "in front of", hebrew: "בפני / מקדימה / לפני" },
    { id: "1_150", english: "in general", hebrew: "באופן כללי" },
    { id: "1_151", english: "in light of", hebrew: "לאור / נוכח" },
    { id: "1_152", english: "in order to", hebrew: "כדי / על מנת" },
    { id: "1_153", english: "in other words", hebrew: "במילים אחרות" },
    { id: "1_154", english: "in particular", hebrew: "במיוחד / בפרט" },
    { id: "1_155", english: "in spite of", hebrew: "למרות / על אף" },
    { id: "1_156", english: "in that case", hebrew: "במקרה כזה" },
    { id: "1_157", english: "in the same way", hebrew: "באותו אופן" },
    { id: "1_158", english: "incidentally", hebrew: "דרך אגב" },
    { id: "1_159", english: "including", hebrew: "כולל" },
    { id: "1_160", english: "indeed", hebrew: "אכן / באמת" },
    { id: "1_161", english: "initially", hebrew: "בתחילה / מלכתחילה" },
    { id: "1_162", english: "inside", hebrew: "בפנים / בתוך" },
    { id: "1_163", english: "instantly", hebrew: "מיידית / בן רגע" },
    { id: "1_164", english: "instead", hebrew: "במקום זאת" },
    { id: "1_165", english: "instead of", hebrew: "במקום" },
    { id: "1_166", english: "into", hebrew: "לתוך / אל תוך" },
    { id: "1_167", english: "just as", hebrew: "בדיוק כמו ש-" },
    { id: "1_168", english: "just as… so…", hebrew: "כשם ש... כך..." },
    { id: "1_169", english: "last", hebrew: "אחרון / שעבר" },
    { id: "1_170", english: "later", hebrew: "מאוחר יותר" },
    { id: "1_171", english: "latter", hebrew: "השני מבין שניים / האחרון" },
    { id: "1_172", english: "led to", hebrew: "הוביל ל-" },
    { id: "1_173", english: "left", hebrew: "שמאל" },
    { id: "1_174", english: "like", hebrew: "כמו" },
    { id: "1_175", english: "likewise", hebrew: "כמו כן / באופן דומה" },
    { id: "1_176", english: "mainly", hebrew: "בעיקר" },
    { id: "1_177", english: "markedly", hebrew: "באופן בולט / ניכר" },
    { id: "1_178", english: "meanwhile", hebrew: "בינתיים" },
    { id: "1_179", english: "moreover", hebrew: "יתרה מכך / בנוסף" },
    { id: "1_180", english: "mostly", hebrew: "לרוב / בעיקר" },
    { id: "1_181", english: "namely", hebrew: "כלומר / דהיינו" },
    { id: "1_182", english: "near", hebrew: "קרוב" },
    { id: "1_183", english: "nearby", hebrew: "בקרבת מקום / סמוך" },
    { id: "1_184", english: "neither... nor…", hebrew: "לא... ולא..." },
    { id: "1_185", english: "never", hebrew: "לעולם לא / אף פעם" },
    { id: "1_186", english: "nevertheless", hebrew: "אף על פי כן / למרות זאת" },
    { id: "1_187", english: "next", hebrew: "הבא / אחר כך" },
    { id: "1_188", english: "next to", hebrew: "ליד / סמוך ל-" },
    { id: "1_189", english: "nonetheless", hebrew: "אף על פי כן" },
    { id: "1_190", english: "not only", hebrew: "לא רק" },
    { id: "1_191", english: "not only... but also…", hebrew: "לא רק... אלא גם..." },
    { id: "1_192", english: "not to mention", hebrew: "שלא לדבר על" },
    { id: "1_193", english: "not... but…", hebrew: "לא... אלא..." },
    { id: "1_194", english: "notably", hebrew: "במיוחד / ראוי לציון" },
    { id: "1_195", english: "now", hebrew: "עכשיו" },
    { id: "1_196", english: "occasionally", hebrew: "מדי פעם / לעיתים" },
    { id: "1_197", english: "of", hebrew: "של / מתוך" },
    { id: "1_198", english: "of course", hebrew: "כמובן" },
    { id: "1_199", english: "of course… but…", hebrew: "כמובן ש... אבל..." },
    { id: "1_200", english: "often", hebrew: "לעיתים קרובות" },
    { id: "1_201", english: "on", hebrew: "על / ב- (תאריכים/ימים)" },
    { id: "1_202", english: "on one hand…on the other hand", hebrew: "מצד אחד... מצד שני" },
    { id: "1_203", english: "on the contrary", hebrew: "נהפוך הוא / להפך" },
    { id: "1_204", english: "on top of", hebrew: "מעל / בנוסף ל-" },
    { id: "1_205", english: "once", hebrew: "פעם אחת / בעבר" },
    { id: "1_206", english: "once", hebrew: "ברגע ש- / כאשר" },
    { id: "1_207", english: "once in a while", hebrew: "מדי פעם" },
    { id: "1_208", english: "only", hebrew: "רק / בלבד" },
    { id: "1_209", english: "opposite", hebrew: "מול / ממול / ההפך" },
    { id: "1_210", english: "or", hebrew: "או" },
    { id: "1_211", english: "ordinarily", hebrew: "בדרך כלל / ברגיל" },
    { id: "1_212", english: "otherwise", hebrew: "אחרת" },
    { id: "1_213", english: "outside", hebrew: "בחוץ" },
    { id: "1_214", english: "outside", hebrew: "מחוץ ל-" },
    { id: "1_215", english: "over", hebrew: "מעל / על פני" },
    { id: "1_216", english: "overall", hebrew: "באופן כללי / כולל" },
    { id: "1_217", english: "owing to", hebrew: "בגלל / הודות ל-" },
    { id: "1_218", english: "particularly", hebrew: "במיוחד / בפרט" },
    { id: "1_219", english: "past", hebrew: "מעבר ל- / עבר" },
    { id: "1_220", english: "permanently", hebrew: "לצמיתות / קבוע" },
    { id: "1_221", english: "perpetually", hebrew: "לנצח / בתמידות" },
    { id: "1_222", english: "presently", hebrew: "כעת / בקרוב" },
    { id: "1_223", english: "previously", hebrew: "קודם לכן / בעבר" },
    { id: "1_224", english: "primarily", hebrew: "בראש ובראשונה / בעיקר" },
    { id: "1_225", english: "prior to", hebrew: "לפני / טרם" },
    { id: "1_226", english: "provided that", hebrew: "בתנאי ש-" },
    { id: "1_227", english: "rarely", hebrew: "לעיתים נדירות" },
    { id: "1_228", english: "rather", hebrew: "למדי / די / אלא" },
    { id: "1_229", english: "rather than", hebrew: "מאשר / במקום" },
    { id: "1_230", english: "regardless", hebrew: "ללא קשר / ללא התחשבות" },
    { id: "1_231", english: "regularly", hebrew: "באופן קבוע" },
    { id: "1_232", english: "right", hebrew: "ימין / צודק / מיד" },
    { id: "1_233", english: "seldom", hebrew: "לעיתים נדירות" },
    { id: "1_234", english: "shortly", hebrew: "בקרוב / זמן קצר לאחר מכן" },
    { id: "1_235", english: "sideways", hebrew: "הצידה" },
    { id: "1_236", english: "significantly", hebrew: "באופן משמעותי" },
    { id: "1_237", english: "similarly", hebrew: "באופן דומה" },
    { id: "1_238", english: "simultaneously", hebrew: "בו זמנית" },
    { id: "1_239", english: "since", hebrew: "מאז / מכיוון ש-" },
    { id: "1_240", english: "since", hebrew: "מכיוון ש-" },
    { id: "1_241", english: "so", hebrew: "לכן / אז / כל כך" },
    { id: "1_242", english: "so long as", hebrew: "כל עוד" },
    { id: "1_243", english: "so that", hebrew: "כדי ש- / על מנת ש-" },
    { id: "1_244", english: "sometimes", hebrew: "לפעמים" },
    { id: "1_245", english: "soon", hebrew: "בקרוב" },
    { id: "1_246", english: "specifically", hebrew: "ספציפית / בייחוד" },
    { id: "1_247", english: "still", hebrew: "עדיין / בכל זאת" },
    { id: "1_248", english: "subsequently", hebrew: "לאחר מכן / כתוצאה מכך" },
    { id: "1_249", english: "such as", hebrew: "כגון / כמו" },
    { id: "1_250", english: "suddenly", hebrew: "פתאום" },
    { id: "1_251", english: "surely", hebrew: "בוודאי / לבטח" },
    { id: "1_252", english: "surprisingly", hebrew: "באופן מפתיע" },
    { id: "1_253", english: "than", hebrew: "מאשר / מ- (השוואה)" },
    { id: "1_254", english: "thanks to", hebrew: "הודות ל-" },
    { id: "1_255", english: "that", hebrew: "ש- / הזה / ההוא" },
    { id: "1_256", english: "then", hebrew: "אז / באותו זמן" },
    { id: "1_257", english: "then", hebrew: "לאחר מכן / אז" },
    { id: "1_258", english: "there", hebrew: "שם" },
    { id: "1_259", english: "therefore", hebrew: "לכן / לפיכך" },
    { id: "1_260", english: "though", hebrew: "למרות ש- / אף על פי ש-" },
    { id: "1_261", english: "though", hebrew: "אבל / עם זאת (בסוף משפט)" },
    { id: "1_262", english: "thus", hebrew: "לפיכך / כך" },
    { id: "1_263", english: "to begin with", hebrew: "קודם כל / בתור התחלה" },
    { id: "1_264", english: "to sum up", hebrew: "לסיכום" },
    { id: "1_265", english: "together with", hebrew: "יחד עם" },
    { id: "1_266", english: "too", hebrew: "גם / יותר מדי" },
    { id: "1_267", english: "too", hebrew: "מדי (לפני תואר)" },
    { id: "1_268", english: "toward", hebrew: "לעבר / לכיוון" },
    { id: "1_269", english: "truly", hebrew: "באמת / בכנות" },
    { id: "1_270", english: "under", hebrew: "מתחת ל- / תחת" },
    { id: "1_271", english: "underneath", hebrew: "מתחת / למטה" },
    { id: "1_272", english: "undoubtedly", hebrew: "ללא ספק" },
    { id: "1_273", english: "unless", hebrew: "אלא אם כן" },
    { id: "1_274", english: "unlike", hebrew: "בניגוד ל- / שונה מ-" },
    { id: "1_275", english: "until", hebrew: "עד / עד ש-" },
    { id: "1_276", english: "until now", hebrew: "עד עכשיו" },
    { id: "1_277", english: "up", hebrew: "למעלה" },
    { id: "1_278", english: "upon", hebrew: "על / בעת / מיד לאחר" },
    { id: "1_279", english: "upside down", hebrew: "הפוך / ראש למטה" },
    { id: "1_280", english: "usually", hebrew: "בדרך כלל" },
    { id: "1_281", english: "vice versa", hebrew: "להפך / וההפך" },
    { id: "1_282", english: "what", hebrew: "מה / איזה" },
    { id: "1_283", english: "when", hebrew: "מתי / כאשר" },
    { id: "1_284", english: "whenever", hebrew: "בכל פעם ש- / מתי ש-" },
    { id: "1_285", english: "where", hebrew: "איפה / היכן" },
    { id: "1_286", english: "where", hebrew: "המקום שבו" },
    { id: "1_287", english: "whereas", hebrew: "ואילו / בעוד ש-" },
    { id: "1_288", english: "wherever", hebrew: "בכל מקום ש- / לאן ש-" },
    { id: "1_289", english: "whether... or…", hebrew: "בין אם... ובין אם..." },
    { id: "1_290", english: "which", hebrew: "איזה / אשר / ש-" },
    { id: "1_291", english: "which", hebrew: "הדבר ש-" },
    { id: "1_292", english: "while", hebrew: "בזמן ש- / בעוד ש- / למרות ש-" },
    { id: "1_293", english: "while", hebrew: "פרק זמן" },
    { id: "1_294", english: "who", hebrew: "מי / אשר / ש- (לאנשים)" },
    { id: "1_295", english: "whom", hebrew: "אותו / למי / אשר (מושא לאנשים)" },
    { id: "1_296", english: "whose", hebrew: "של מי / אשר שלו" },
    { id: "1_297", english: "why", hebrew: "למה / מדוע" },
    { id: "1_298", english: "with", hebrew: "עם / באמצעות" },
    { id: "1_299", english: "within", hebrew: "בתוך / במסגרת (זמן/מקום)" },
    { id: "1_300", english: "without", hebrew: "בלי / ללא" },
    { id: "1_301", english: "yet", hebrew: "עדיין (בשאלה/שלילה)" },
    { id: "1_302", english: "yet", hebrew: "אולם / עם זאת" }
  ],
  "2": [
    { id: "2_1", english: "ability", hebrew: "יכולת" },
    { id: "2_2", english: "able", hebrew: "מסוגל" },
    { id: "2_3", english: "accept", hebrew: "לקבל / להסכים" },
    { id: "2_4", english: "acceptable", hebrew: "קביל / מקובל" },
    { id: "2_5", english: "acceptance", hebrew: "קבלה / הסכמה" },
    { id: "2_6", english: "accident", hebrew: "תאונה" },
    { id: "2_7", english: "achieve", hebrew: "להשיג / להגיע להישג" },
    { id: "2_8", english: "activate", hebrew: "להפעיל" },
    { id: "2_9", english: "active", hebrew: "פעיל" },
    { id: "2_10", english: "actor", hebrew: "שחקן" },
    { id: "2_11", english: "actual", hebrew: "ממשי / בפועל" },
    { id: "2_12", english: "actually", hebrew: "בעצם / למעשה" },
    { id: "2_13", english: "addition", hebrew: "תוספת / חיבור" },
    { id: "2_14", english: "address", hebrew: "כתובת / לנאום / לפנות אל" },
    { id: "2_15", english: "adjust", hebrew: "להתאים / לכוונן / להתרגל" },
    { id: "2_16", english: "afford", hebrew: "להרשות לעצמו כספית" },
    { id: "2_17", english: "afraid", hebrew: "מפוחד / חושש" },
    { id: "2_18", english: "agree", hebrew: "להסכים" },
    { id: "2_19", english: "agreement", hebrew: "הסכם / קבוצה" },
    { id: "2_20", english: "aim", hebrew: "מטרה / לכוון" },
    { id: "2_21", english: "alarm", hebrew: "אזעקה / להבהיל" },
    { id: "2_22", english: "alive", hebrew: "חי / בחיים" },
    { id: "2_23", english: "almost", hebrew: "כמעט" },
    { id: "2_24", english: "alone", hebrew: "לבד" },
    { id: "2_25", english: "alternate", hebrew: "לסירוגין / חלופי" },
    { id: "2_26", english: "altogether", hebrew: "לחלוטין / סך הכל" },
    { id: "2_27", english: "ambassador", hebrew: "שגריר" },
    { id: "2_28", english: "ambiguous", hebrew: "מעורפל / דו-משמעי" },
    { id: "2_29", english: "amount", hebrew: "כמות / סכום" },
    { id: "2_30", english: "anger", hebrew: "כעס / לכעוס" },
    { id: "2_31", english: "angry", hebrew: "כועס" },
    { id: "2_32", english: "animal", hebrew: "חיה / בעל חיים" },
    { id: "2_33", english: "another", hebrew: "אחר / נוסף / עוד אחד" },
    { id: "2_34", english: "answer", hebrew: "תשובה / לענות" },
    { id: "2_35", english: "apart", hebrew: "בנפרד / לחוד" },
    { id: "2_36", english: "apology", hebrew: "התנצלות" },
    { id: "2_37", english: "appear", hebrew: "להופיע / להיראות" },
    { id: "2_38", english: "appearance", hebrew: "הופעה / מראה חיצוני" },
    { id: "2_39", english: "appropriate", hebrew: "מתאים / הולם" },
    { id: "2_40", english: "approve", hebrew: "לאשר / להסכים ל-" },
    { id: "2_41", english: "architect", hebrew: "אדריכל" },
    { id: "2_42", english: "architecture", hebrew: "אדריכלות" },
    { id: "2_43", english: "area", hebrew: "אזור / שטח" },
    { id: "2_44", english: "argue", hebrew: "להתווכח / לטעון" },
    { id: "2_45", english: "argument", hebrew: "טיעון / ויכוח" },
    { id: "2_46", english: "characterize", hebrew: "לאפיין" },
    { id: "2_47", english: "cheap", hebrew: "זול" },
    { id: "2_48", english: "check", hebrew: "לבדוק / בדיקה / צ'ק" },
    { id: "2_49", english: "child", hebrew: "ילד" },
    { id: "2_50", english: "childhood", hebrew: "ילדות" },
    { id: "2_51", english: "children", hebrew: "ילדים" },
    { id: "2_52", english: "circle", hebrew: "עיגול / להקיף בעיגול" },
    { id: "2_53", english: "clean", hebrew: "נקי / לנקות" },
    { id: "2_54", english: "clever", hebrew: "חכם / פיקח" },
    { id: "2_55", english: "climb", hebrew: "לטפס / טיפוס" },
    { id: "2_56", english: "clock", hebrew: "שעון קיר" },
    { id: "2_57", english: "close", hebrew: "לסגור / קרוב" },
    { id: "2_58", english: "cloth", hebrew: "בד / מטלית" },
    { id: "2_59", english: "coach", hebrew: "מאמן / כרכרה" },
    { id: "2_60", english: "code", hebrew: "קוד" },
    { id: "2_61", english: "coexist", hebrew: "לחיות בדו-קיום" },
    { id: "2_62", english: "coin", hebrew: "מטבע" },
    { id: "2_63", english: "cold", hebrew: "קר / צינון" },
    { id: "2_64", english: "complain", hebrew: "להתלונן" },
    { id: "2_65", english: "complete", hebrew: "שלם / להשלים / לסיים" },
    { id: "2_66", english: "consist", hebrew: "להיות מורכב מ-" },
    { id: "2_67", english: "contact", hebrew: "קשר / ליצור קשר" },
    { id: "2_68", english: "continue", hebrew: "להמשיך" },
    { id: "2_69", english: "control", hebrew: "שליטה / לשלוט" },
    { id: "2_70", english: "correct", hebrew: "נכון / לתקן" },
    { id: "2_71", english: "cost", hebrew: "עלות / לעלות מחיר" },
    { id: "2_72", english: "count", hebrew: "לספור / להחשיב" },
    { id: "2_73", english: "country", hebrew: "מדינה / אזור כפרי" },
    { id: "2_74", english: "cover", hebrew: "לכסות / כיסוי / עטיפה" },
    { id: "2_75", english: "danger", hebrew: "סכנה" },
    { id: "2_76", english: "dangerous", hebrew: "מסוכן" },
    { id: "2_77", english: "death", hebrew: "מוות" },
    { id: "2_78", english: "deep", hebrew: "עמוק" },
    { id: "2_79", english: "define", hebrew: "להגדיר" },
    { id: "2_80", english: "delete", hebrew: "למחוק" },
    { id: "2_81", english: "die", hebrew: "למות" },
    { id: "2_82", english: "difficult", hebrew: "קשה / מורכב" },
    { id: "2_83", english: "dirty", hebrew: "מלוכלך" },
    { id: "2_84", english: "dream", hebrew: "חלום / לחלום" },
    { id: "2_85", english: "drink", hebrew: "לשתות / משקה" },
    { id: "2_86", english: "early", hebrew: "מוקדם" },
    { id: "2_87", english: "earth", hebrew: "אדמה / עפר" },
    { id: "2_88", english: "education", hebrew: "חינוך" },
    { id: "2_89", english: "empty", hebrew: "ריק / לרוקן" },
    { id: "2_90", english: "enemy", hebrew: "אויב" },
    { id: "2_91", english: "enjoy", hebrew: "ליהנות מ-" },
    { id: "2_92", english: "error", hebrew: "שגיאה / טעות" },
    { id: "2_93", english: "escape", hebrew: "לברוח / בריחה" },
    { id: "2_94", english: "evening", hebrew: "ערב" },
    { id: "2_95", english: "event", hebrew: "אירוע" },
    { id: "2_96", english: "exactly", hebrew: "בבדיוק" },
    { id: "2_97", english: "example", hebrew: "דוגמה" },
    { id: "2_98", english: "expert", hebrew: "מומחה" },
    { id: "2_99", english: "fact", hebrew: "עובדה" },
    { id: "2_100", english: "false", hebrew: "שקרי / שגויה" },
    { id: "2_101", english: "fear", hebrew: "פחד / לפחד" },
    { id: "2_102", english: "feel", hebrew: "להרגיש / תחושה" },
    { id: "2_103", english: "find", hebrew: "למצוא" },
    { id: "2_104", english: "fix", hebrew: "לתקן / לקבוע" },
    { id: "2_105", english: "forget", hebrew: "לשכוח" },
    { id: "2_106", english: "friend", hebrew: "חבר" },
    { id: "2_107", english: "full", hebrew: "מלא" },
    { id: "2_108", english: "great", hebrew: "נהדר / גדול" },
    { id: "2_109", english: "hear", hebrew: "לשמוע" },
    { id: "2_110", english: "heavy", hebrew: "כבד" },
    { id: "2_111", english: "hero", hebrew: "גיבור" },
    { id: "2_112", english: "hot", hebrew: "חם / חריף" },
    { id: "2_113", english: "house", hebrew: "בית" },
    { id: "2_114", english: "identify", hebrew: "לזהות" },
    { id: "2_115", english: "important", hebrew: "חשוב" },
    { id: "2_116", english: "jump", hebrew: "לקפוץ" },
    { id: "2_117", english: "kill", hebrew: "להרוג" },
    { id: "2_118", english: "kitchen", hebrew: "מטבח" },
    { id: "2_119", english: "last", hebrew: "אחרון / להחזיק מעמד" },
    { id: "2_120", english: "late", hebrew: "מאוחר" },
    { id: "2_121", english: "light", hebrew: "אור / קל" },
    { id: "2_122", english: "list", hebrew: "רשימה" },
    { id: "2_123", english: "lock", hebrew: "לנעול" },
    { id: "2_124", english: "logic", hebrew: "היגיון" },
    { id: "2_125", english: "main", hebrew: "עיקרי / מרכזי" },
    { id: "2_126", english: "maybe", hebrew: "אולי" },
    { id: "2_127", english: "mistake", hebrew: "טעות" },
    { id: "2_128", english: "money", hebrew: "כסף" },
    { id: "2_129", english: "move", hebrew: "לזוז / להניע" },
    { id: "2_130", english: "must", hebrew: "חייב / חובה" },
    { id: "2_131", english: "open", hebrew: "פתוח / לפתוח" },
    { id: "2_132", english: "peace", hebrew: "שלום" },
    { id: "2_133", english: "plan", hebrew: "תוכנית / לתכנן" },
    { id: "2_134", english: "problem", hebrew: "בעיה" },
    { id: "2_135", english: "quick", hebrew: "מהיר" },
    { id: "2_136", english: "rest", hebrew: "מנוחה / לנוח / השאר" },
    { id: "2_137", english: "rich", hebrew: "עשיר" },
    { id: "2_138", english: "right", hebrew: "ימין / צדק" },
    { id: "2_139", english: "risk", hebrew: "סיכון" },
    { id: "2_140", english: "safe", hebrew: "בטוח" },
    { id: "2_141", english: "save", hebrew: "להציל / לשמור / לחסוך" },
    { id: "2_142", english: "search", hebrew: "לחפש" },
    { id: "2_143", english: "sell", hebrew: "למכור" },
    { id: "2_144", english: "send", hebrew: "לשלוח" },
    { id: "2_145", english: "short", hebrew: "קצר" },
    { id: "2_146", english: "slow", hebrew: "איטי" },
    { id: "2_147", english: "space", hebrew: "חלל / מרחב" },
    { id: "2_148", english: "speed", hebrew: "מהירות" },
    { id: "2_149", english: "start", hebrew: "להתחיל" },
    { id: "2_150", english: "strong", hebrew: "חזק" },
    { id: "2_151", english: "system", hebrew: "מערכת" },
    { id: "2_152", english: "understand", hebrew: "להבין" },
    { id: "2_153", english: "unusual", hebrew: "חריג / בלתי רגיל" },
    { id: "2_154", english: "useful", hebrew: "שימושי" },
    { id: "2_155", english: "usual", hebrew: "רגיל" },
    { id: "2_156", english: "value", hebrew: "ערך" },
    { id: "2_157", english: "view", hebrew: "נוף / השקפה" },
    { id: "2_158", english: "visit", hebrew: "לבקר" },
    { id: "2_159", english: "voice", hebrew: "קול" },
    { id: "2_160", english: "wait", hebrew: "לחכות" },
    { id: "2_161", english: "way", hebrew: "דרך / אופן" },
    { id: "2_162", english: "weather", hebrew: "מזג אוויר" }
  ],
  "3": [
    { id: "3_1", english: "abrupt", hebrew: "פתאומי / מפתיע" },
    { id: "3_2", english: "absolute", hebrew: "מוחלט" },
    { id: "3_3", english: "accomplish", hebrew: "להשיג / לבצע" },
    { id: "3_4", english: "accurate", hebrew: "מדויק" },
    { id: "3_5", english: "adapt", hebrew: "להתאים / להסתגל" },
    { id: "3_6", english: "admit", hebrew: "להודות / לאפשר כניסה" },
    { id: "3_7", english: "advance", hebrew: "להתקדם" },
    { id: "3_8", english: "advantage", hebrew: "יתרון" },
    { id: "3_9", english: "advice", hebrew: "עצה" },
    { id: "3_10", english: "brief", hebrew: "קצר / תמציתי" },
    { id: "3_11", english: "confirm", hebrew: "לאשר / לאמת" },
    { id: "3_12", english: "crisis", hebrew: "משבר" },
    { id: "3_13", english: "evaluate", hebrew: "להעריך" },
    { id: "3_14", english: "profound", hebrew: "עמוק / מעמיק" },
    { id: "3_15", english: "reveal", hebrew: "לחשוף / לגלות" }
  ],
  "4": [
    { id: "4_1", english: "abandon", hebrew: "לנטוש" },
    { id: "4_2", english: "accumulate", hebrew: "לצבור / לאגור" },
    { id: "4_3", english: "acquire", hebrew: "לרכוש / להשיג" },
    { id: "4_4", english: "cautious", hebrew: "זהיר" },
    { id: "4_5", english: "profoundly", hebrew: "עמוקות" },
    { id: "4_6", english: "strive", hebrew: "לשאוף / לחתור בתוקף" }
  ]
};