// src/words.js

export const UNITS_DATA = [
  { id: "1", name: "יחידה 1: מילות קישור, זמן ומיקום" },
  { id: "2", name: "יחידה 2: אוצר מילים כללי ופעלים מרכזיים" },
  { id: "3", name: "יחידה 3: אוצר מילים מתקדמת ואקדמית" },
  { id: "4", name: "יחידה 4: אוצר מילים מורחב וביטויים נפוצים" }
];

export const WORDS_DATA = {
  "1": [
    { id: "1_1", english: "10th - tenth", hebrew: "עשירי" },
    { id: "1_2", english: "1st - first", hebrew: "ראשון" },
    { id: "1_3", english: "2nd - second", hebrew: "שני" },
    { id: "1_4", english: "3rd - third", hebrew: "שלישי" },
    { id: "1_5", english: "4th - fourth", hebrew: "רביעי" },
    { id: "1_6", english: "5th - fifth", hebrew: "חמישי" },
    { id: "1_7", english: "6th - sixth", hebrew: "שישי" },
    { id: "1_8", english: "7th - seventh", hebrew: "שביעי" },
    { id: "1_9", english: "8th - eighth", hebrew: "שמיני" },
    { id: "1_10", english: "9th - ninth", hebrew: "תשיעי" },
    { id: "1_11", english: "about", hebrew: "אודות / על" },
    { id: "1_12", english: "about", hebrew: "בערך / סביב" },
    { id: "1_13", english: "above", hebrew: "מעל" },
    { id: "1_14", english: "above all", hebrew: "מעל הכל / בראש ובראשונה" },
    { id: "1_15", english: "absolutely", hebrew: "לחלוטין / בהחלט" },
    { id: "1_16", english: "according", hebrew: "לפי / בהתאם ל-" },
    { id: "1_17", english: "accordingly", hebrew: "בהתאם לכך" },
    { id: "1_18", english: "across", hebrew: "מעבר ל- / ברחבי" },
    { id: "1_19", english: "additionally", hebrew: "בנוסף לכך" },
    { id: "1_20", english: "adjacent to", hebrew: "סמוך ל- / ליד" },
    { id: "1_21", english: "after", hebrew: "אחרי / לאחר" },
    { id: "1_22", english: "after all", hebrew: "אחרי הכל" },
    { id: "1_23", english: "after all", hebrew: "למרות הכל" },
    { id: "1_24", english: "afterwards", hebrew: "לאחר מכן" },
    { id: "1_25", english: "again", hebrew: "שוב" },
    { id: "1_26", english: "against", hebrew: "נגד / כנגד" },
    { id: "1_27", english: "ahead of", hebrew: "לפני (בזמן/מקום)" },
    { id: "1_28", english: "albeit", hebrew: "אם כי / אף על פי ש-" },
    { id: "1_29", english: "all in all", hebrew: "בסך הכל" },
    { id: "1_30", english: "along", hebrew: "לאורך" },
    { id: "1_31", english: "along with", hebrew: "יחד עם" },
    { id: "1_32", english: "alongside", hebrew: "לצד / במקביל" },
    { id: "1_33", english: "also", hebrew: "גם / בנוסף" },
    { id: "1_34", english: "although", hebrew: "למרות ש-" },
    { id: "1_35", english: "altogether", hebrew: "לגמרי / בסך הכל" },
    { id: "1_36", english: "always", hebrew: "תמיד" },
    { id: "1_37", english: "amid", hebrew: "בקרב / בתוך" },
    { id: "1_38", english: "among", hebrew: "בין (רבים) / בקרב" },
    { id: "1_39", english: "and", hebrew: "ו- / וגם" },
    { id: "1_40", english: "around", hebrew: "מסביב / בערך" },
    { id: "1_41", english: "as", hebrew: "כמו / בתור" },
    { id: "1_42", english: "as", hebrew: "מכיוון ש- / כש-" },
    { id: "1_43", english: "as a result", hebrew: "כתוצאה מכך" },
    { id: "1_44", english: "as if", hebrew: "כאילו" },
    { id: "1_45", english: "as long as", hebrew: "כל עוד" },
    { id: "1_46", english: "as soon as", hebrew: "ברגע ש- / בהקדם" },
    { id: "1_47", english: "as well as", hebrew: "כמו גם / בנוסף ל-" },
    { id: "1_48", english: "aside from", hebrew: "מלבד / חוץ מ-" },
    { id: "1_49", english: "at", hebrew: "ב- / אצל / בתוך" },
    { id: "1_50", english: "at first", hebrew: "בהתחלה" },
    { id: "1_51", english: "at last", hebrew: "לבסוף" },
    { id: "1_52", english: "backward", hebrew: "אחורה / לאחור" },
    { id: "1_53", english: "based on", hebrew: "מבוסס על" },
    { id: "1_54", english: "because", hebrew: "בגלל ש- / כי" },
    { id: "1_55", english: "because of", hebrew: "בגלל / בעקבות" },
    { id: "1_56", english: "before", hebrew: "לפני" },
    { id: "1_57", english: "before", hebrew: "בטרם" },
    { id: "1_58", english: "behind", hebrew: "מאחורי" },
    { id: "1_59", english: "being that", hebrew: "היות ש- / מכיוון ש-" },
    { id: "1_60", english: "below", hebrew: "מתחת" },
    { id: "1_61", english: "beneath", hebrew: "מתחת ל- / למטה מ-" },
    { id: "1_62", english: "beside", hebrew: "לצד / על יד" },
    { id: "1_63", english: "besides", hebrew: "חוץ מזה / מלבד" },
    { id: "1_64", english: "besides", hebrew: "בנוסף ל-" },
    { id: "1_65", english: "besides", hebrew: "יתר על כן" },
    { id: "1_66", english: "between", hebrew: "בין (שניים)" },
    { id: "1_67", english: "beyond", hebrew: "מעבר ל-" },
    { id: "1_68", english: "both", hebrew: "שניהם / שתי-" },
    { id: "1_69", english: "both... and…", hebrew: "גם... וגם..." },
    { id: "1_70", english: "but", hebrew: "אבל" },
    { id: "1_71", english: "but", hebrew: "אלא / פרט ל-" },
    { id: "1_72", english: "by", hebrew: "על ידי / באמצעות" },
    { id: "1_73", english: "by", hebrew: "עד (זמן) / ליד" },
    { id: "1_74", english: "certainly", hebrew: "בוודאות / בהחלט" },
    { id: "1_75", english: "chiefly", hebrew: "בעיקר" },
    { id: "1_76", english: "close", hebrew: "קרוב / סמוך" },
    { id: "1_77", english: "comparatively", hebrew: "באופן יחסי" },
    { id: "1_78", english: "consequently", hebrew: "כתוצאה מכך" },
    { id: "1_79", english: "consistently", hebrew: "בעקביות / באופן עקבי" },
    { id: "1_80", english: "constantly", hebrew: "כל הזמן / בתמידות" },
    { id: "1_81", english: "contradictory", hebrew: "סותר / נוגד" },
    { id: "1_82", english: "contrary", hebrew: "מנוגד / ההפך" },
    { id: "1_83", english: "conversely", hebrew: "להפך / מאידך גיסא" },
    { id: "1_84", english: "correspondingly", hebrew: "בהתאמה" },
    { id: "1_85", english: "coupled with", hebrew: "בשילוב עם" },
    { id: "1_86", english: "currently", hebrew: "כעת / כרגע" },
    { id: "1_87", english: "daily", hebrew: "יומי / מדי יום" },
    { id: "1_88", english: "despite", hebrew: "למרות / על אף" },
    { id: "1_89", english: "different from", hebrew: "שונה מ-" },
    { id: "1_90", english: "distant", hebrew: "רחוק" },
    { id: "1_91", english: "down", hebrew: "למטה" },
    { id: "1_92", english: "due to", hebrew: "עקב / בגלל" },
    { id: "1_93", english: "during", hebrew: "במהלך / במשך" },
    { id: "1_94", english: "e.g.", hebrew: "לדוגמה (למשל)" },
    { id: "1_95", english: "earlier", hebrew: "מוקדם יותר" },
    { id: "1_96", english: "either... or…", hebrew: "או... או..." },
    { id: "1_97", english: "elsewhere", hebrew: "במקום אחר" },
    { id: "1_98", english: "equally", hebrew: "במידה שווה" },
    { id: "1_99", english: "especially", hebrew: "במיוחד" },
    { id: "1_100", english: "essentially", hebrew: "בעיקרו של דבר / ביסודו" },
    { id: "1_101", english: "even if", hebrew: "אפילו אם" },
    { id: "1_102", english: "even so", hebrew: "אף על פי כן / למרות זאת" },
    { id: "1_103", english: "even though", hebrew: "אף על פי ש- / למרות ש-" },
    { id: "1_104", english: "eventually", hebrew: "בסופו של דבר" },
    { id: "1_105", english: "every day", hebrew: "כל יום" },
    { id: "1_106", english: "every now and then", hebrew: "מדי פעם" },
    { id: "1_107", english: "except", hebrew: "חוץ מ- / פרט ל-" },
    { id: "1_108", english: "farther", hebrew: "רחוק יותר (פיזית)" },
    { id: "1_109", english: "finally", hebrew: "לבסוף" },
    { id: "1_110", english: "first of all", hebrew: "קודם כל / ראשית" },
    { id: "1_111", english: "for", hebrew: "בשביל / עבור" },
    { id: "1_112", english: "for", hebrew: "כי / מכיוון ש- / במשך (זמן)" },
    { id: "1_113", english: "for example", hebrew: "לדוגמה" },
    { id: "1_114", english: "for instance", hebrew: "למשל" },
    { id: "1_115", english: "for the most part", hebrew: "לרוב / בדרך כלל" },
    { id: "1_116", english: "forever", hebrew: "לתמיד / לעד" },
    { id: "1_117", english: "former", hebrew: "קודם / לשעבר" },
    { id: "1_118", english: "forward", hebrew: "קדימה" },
    { id: "1_119", english: "frequently", hebrew: "לעיתים קרובות" },
    { id: "1_120", english: "from", hebrew: "מ- / מתוך" },
    { id: "1_121", english: "from", hebrew: "מאת" },
    { id: "1_122", english: "from time to time", hebrew: "מדי פעם" },
    { id: "1_123", english: "further", hebrew: "הלאה / עוד" },
    { id: "1_124", english: "further", hebrew: "נוסך / מעבר לכך" },
    { id: "1_125", english: "furthermore", hebrew: "יתרה מכך / זאת ועוד" },
    { id: "1_126", english: "given that", hebrew: "בהתחשב בכך ש-" },
    { id: "1_127", english: "granted (that)", hebrew: "אמנם / בהנחה ש-" },
    { id: "1_128", english: "hardly ever", hebrew: "כמעט אף פעם לא" },
    { id: "1_129", english: "hence", hebrew: "לפיכך / משום כך" },
    { id: "1_130", english: "here", hebrew: "כאן / פה" },
    { id: "1_131", english: "how", hebrew: "איך / כיצד" },
    { id: "1_132", english: "however", hebrew: "אולם / יחד עם זאת" },
    { id: "1_133", english: "however", hebrew: "בכל דרך ש-" },
    { id: "1_134", english: "i.e.", hebrew: "כלומר / דהיינו" },
    { id: "1_135", english: "identically", hebrew: "באופן זהה" },
    { id: "1_136", english: "If", hebrew: "אם" },
    { id: "1_137", english: "immediately", hebrew: "מיד / באופן מיידי" },
    { id: "1_138", english: "in", hebrew: "ב- / בתוך" },
    { id: "1_139", english: "in a moment", hebrew: "בעוד רגע / מיד" },
    { id: "1_140", english: "in a word", hebrew: "במילה אחת" },
    { id: "1_141", english: "in addition", hebrew: "בנוסף / יתר על כן" },
    { id: "1_142", english: "in case", hebrew: "במקרה ש- / למקרה ש-" },
    { id: "1_143", english: "in comparison", hebrew: "בהשוואה" },
    { id: "1_144", english: "in conclusion", hebrew: "לסיכום" },
    { id: "1_145", english: "in contrast to", hebrew: "בניגוד ל-" },
    { id: "1_146", english: "in due time", hebrew: "בבוא הזמן" },
    { id: "1_147", english: "in fact", hebrew: "למעשה" },
    { id: "1_148", english: "in fact", hebrew: "בעצם" },
    { id: "1_149", english: "in front of", hebrew: "בפני / מקדימה / לפני" },
    { id: "1_150", english: "in general", hebrew: "באופן כללי" },
    { id: "1_151", english: "in light of", hebrew: "לאור / נוכח" },
    { id: "1_152", english: "in order to", hebrew: "כדי / על מנת" },
    { id: "1_153", english: "in other words", hebrew: "במילים אחרות" },
    { id: "1_154", english: "in particular", hebrew: "במיוחד / בפרט" },
    { id: "1_155", english: "in spite of", hebrew: "למרות / על אף" },
    { id: "1_156", english: "in that case", hebrew: "במקרה כזה" },
    { id: "1_157", english: "in the same way", hebrew: "באותו אופן" },
    { id: "1_158", english: "incidentally", hebrew: "דרך אגב" },
    { id: "1_159", english: "including", hebrew: "כולל" },
    { id: "1_160", english: "indeed", hebrew: "אכן / באמת" },
    { id: "1_161", english: "initially", hebrew: "בתחילה / מלכתחילה" },
    { id: "1_162", english: "inside", hebrew: "בפנים / בתוך" },
    { id: "1_163", english: "instantly", hebrew: "מיידית / בן רגע" },
    { id: "1_164", english: "instead", hebrew: "במקום זאת" },
    { id: "1_165", english: "instead of", hebrew: "במקום" },
    { id: "1_166", english: "into", hebrew: "לתוך / אל תוך" },
    { id: "1_167", english: "just as", hebrew: "בדיוק כמו ש-" },
    { id: "1_168", english: "just as… so…", hebrew: "כשם ש... כך..." },
    { id: "1_169", english: "last", hebrew: "אחרון / שעבר" },
    { id: "1_170", english: "later", hebrew: "מאוחר יותר" },
    { id: "1_171", english: "latter", hebrew: "השני מבין שניים / האחרון" },
    { id: "1_172", english: "led to", hebrew: "הוביל ל-" },
    { id: "1_173", english: "left", hebrew: "שמאל" },
    { id: "1_174", english: "like", hebrew: "כמו" },
    { id: "1_175", english: "likewise", hebrew: "כמו כן / באופן דומה" },
    { id: "1_176", english: "mainly", hebrew: "בעיקר" },
    { id: "1_177", english: "markedly", hebrew: "באופן בולט / ניכר" },
    { id: "1_178", english: "meanwhile", hebrew: "בינתיים" },
    { id: "1_179", english: "moreover", hebrew: "יתרה מכך / בנוסף" },
    { id: "1_180", english: "mostly", hebrew: "לרוב / בעיקר" },
    { id: "1_181", english: "namely", hebrew: "כלומר / דהיינו" },
    { id: "1_182", english: "near", hebrew: "קרוב" },
    { id: "1_183", english: "nearby", hebrew: "בקרבת מקום / סמוך" },
    { id: "1_184", english: "neither... nor…", hebrew: "לא... ולא..." },
    { id: "1_185", english: "never", hebrew: "לעולם לא / אף פעם" },
    { id: "1_186", english: "nevertheless", hebrew: "אף על פי כן / למרות זאת" },
    { id: "1_187", english: "next", hebrew: "הבא / אחר כך" },
    { id: "1_188", english: "next to", hebrew: "ליד / סמוך ל-" },
    { id: "1_189", english: "nonetheless", hebrew: "אף על פי כן" },
    { id: "1_190", english: "not only", hebrew: "לא רק" },
    { id: "1_191", english: "not only... but also…", hebrew: "לא רק... אלא גם..." },
    { id: "1_192", english: "not to mention", hebrew: "שלא לדבר על" },
    { id: "1_193", english: "not... but…", hebrew: "לא... אלא..." },
    { id: "1_194", english: "notably", hebrew: "במיוחד / ראוי לציון" },
    { id: "1_195", english: "now", hebrew: "עכשיו" },
    { id: "1_196", english: "occasionally", hebrew: "מדי פעם / לעיתים" },
    { id: "1_197", english: "of", hebrew: "של / מתוך" },
    { id: "1_198", english: "of course", hebrew: "כמובן" },
    { id: "1_199", english: "of course… but…", hebrew: "כמובן ש... אבל..." },
    { id: "1_200", english: "often", hebrew: "לעיתים קרובות" },
    { id: "1_201", english: "on", hebrew: "על / ב- (תאריכים/ימים)" },
    { id: "1_202", english: "on one hand…on the other hand", hebrew: "מצד אחד... מצד שני" },
    { id: "1_203", english: "on the contrary", hebrew: "נהפוך הוא / להפך" },
    { id: "1_204", english: "on top of", hebrew: "מעל / בנוסף ל-" },
    { id: "1_205", english: "once", hebrew: "פעם אחת / בעבר" },
    { id: "1_206", english: "once", hebrew: "ברגע ש- / כאשר" },
    { id: "1_207", english: "once in a while", hebrew: "מדי פעם" },
    { id: "1_208", english: "only", hebrew: "רק / בלבד" },
    { id: "1_209", english: "opposite", hebrew: "מול / ממול / ההפך" },
    { id: "1_210", english: "or", hebrew: "או" },
    { id: "1_211", english: "ordinarily", hebrew: "בדרך כלל / ברגיל" },
    { id: "1_212", english: "otherwise", hebrew: "אחרת" },
    { id: "1_213", english: "outside", hebrew: "בחוץ" },
    { id: "1_214", english: "outside", hebrew: "מחוץ ל-" },
    { id: "1_215", english: "over", hebrew: "מעל / על פני" },
    { id: "1_216", english: "overall", hebrew: "באופן כללי / כולל" },
    { id: "1_217", english: "owing to", hebrew: "בגלל / הודות ל-" },
    { id: "1_218", english: "particularly", hebrew: "במיוחד / בפרט" },
    { id: "1_219", english: "past", hebrew: "מעבר ל- / עבר" },
    { id: "1_220", english: "permanently", hebrew: "לצמיתות / קבוע" },
    { id: "1_221", english: "perpetually", hebrew: "לנצח / בתמידות" },
    { id: "1_222", english: "presently", hebrew: "כעת / בקרוב" },
    { id: "1_223", english: "previously", hebrew: "קודם לכן / בעבר" },
    { id: "1_224", english: "primarily", hebrew: "בראש ובראשונה / בעיקר" },
    { id: "1_225", english: "prior to", hebrew: "לפני / טרם" },
    { id: "1_226", english: "provided that", hebrew: "בתנאי ש-" },
    { id: "1_227", english: "rarely", hebrew: "לעיתים נדירות" },
    { id: "1_228", english: "rather", hebrew: "למדי / די / אלא" },
    { id: "1_229", english: "rather than", hebrew: "מאשר / במקום" },
    { id: "1_230", english: "regardless", hebrew: "ללא קשר / ללא התחשבות" },
    { id: "1_231", english: "regularly", hebrew: "באופן קבוע" },
    { id: "1_232", english: "right", hebrew: "ימין / צודק / מיד" },
    { id: "1_233", english: "seldom", hebrew: "לעיתים נדירות" },
    { id: "1_234", english: "shortly", hebrew: "בקרוב / זמן קצר לאחר מכן" },
    { id: "1_235", english: "sideways", hebrew: "הצידה" },
    { id: "1_236", english: "significantly", hebrew: "באופן משמעותי" },
    { id: "1_237", english: "similarly", hebrew: "באופן דומה" },
    { id: "1_238", english: "simultaneously", hebrew: "בו זמנית" },
    { id: "1_239", english: "since", hebrew: "מאז / מכיוון ש-" },
    { id: "1_240", english: "since", hebrew: "מכיוון ש-" },
    { id: "1_241", english: "so", hebrew: "לכן / אז / כל כך" },
    { id: "1_242", english: "so long as", hebrew: "כל עוד" },
    { id: "1_243", english: "so that", hebrew: "כדי ש- / על מנת ש-" },
    { id: "1_244", english: "sometimes", hebrew: "לפעמים" },
    { id: "1_245", english: "soon", hebrew: "בקרוב" },
    { id: "1_246", english: "specifically", hebrew: "ספציפית / בייחוד" },
    { id: "1_247", english: "still", hebrew: "עדיין / בכל זאת" },
    { id: "1_248", english: "subsequently", hebrew: "לאחר מכן / כתוצאה מכך" },
    { id: "1_249", english: "such as", hebrew: "כגון / כמו" },
    { id: "1_250", english: "suddenly", hebrew: "פתאום" },
    { id: "1_251", english: "surely", hebrew: "בוודאי / לבטח" },
    { id: "1_252", english: "surprisingly", hebrew: "באופן מפתיע" },
    { id: "1_253", english: "than", hebrew: "מאשר / מ- (השוואה)" },
    { id: "1_254", english: "thanks to", hebrew: "הודות ל-" },
    { id: "1_255", english: "that", hebrew: "ש- / הזה / ההוא" },
    { id: "1_256", english: "then", hebrew: "אז / באותו זמן" },
    { id: "1_257", english: "then", hebrew: "לאחר מכן / אז" },
    { id: "1_258", english: "there", hebrew: "שם" },
    { id: "1_259", english: "therefore", hebrew: "לכן / לפיכך" },
    { id: "1_260", english: "though", hebrew: "למרות ש- / אף על פי ש-" },
    { id: "1_261", english: "though", hebrew: "אבל / עם זאת (בסוף משפט)" },
    { id: "1_262", english: "thus", hebrew: "לפיכך / כך" },
    { id: "1_263", english: "to begin with", hebrew: "קודם כל / בתור התחלה" },
    { id: "1_264", english: "to sum up", hebrew: "לסיכום" },
    { id: "1_265", english: "together with", hebrew: "יחד עם" },
    { id: "1_266", english: "too", hebrew: "גם / יותר מדי" },
    { id: "1_267", english: "too", hebrew: "מדי (לפני תואר)" },
    { id: "1_268", english: "toward", hebrew: "לעבר / לכיוון" },
    { id: "1_269", english: "truly", hebrew: "באמת / בכנות" },
    { id: "1_270", english: "under", hebrew: "מתחת ל- / תחת" },
    { id: "1_271", english: "underneath", hebrew: "מתחת / למטה" },
    { id: "1_272", english: "undoubtedly", hebrew: "ללא ספק" },
    { id: "1_273", english: "unless", hebrew: "אלא אם כן" },
    { id: "1_274", english: "unlike", hebrew: "בניגוד ל- / שונה מ-" },
    { id: "1_275", english: "until", hebrew: "עד / עד ש-" },
    { id: "1_276", english: "until now", hebrew: "עד עכשיו" },
    { id: "1_277", english: "up", hebrew: "למעלה" },
    { id: "1_278", english: "upon", hebrew: "על / בעת / מיד לאחר" },
    { id: "1_279", english: "upside down", hebrew: "הפוך / ראש למטה" },
    { id: "1_280", english: "usually", hebrew: "בדרך כלל" },
    { id: "1_281", english: "vice versa", hebrew: "להפך / וההפך" },
    { id: "1_282", english: "what", hebrew: "מה / איזה" },
    { id: "1_283", english: "when", hebrew: "מתי / כאשר" },
    { id: "1_284", english: "whenever", hebrew: "בכל פעם ש- / מתי ש-" },
    { id: "1_285", english: "where", hebrew: "איפה / היכן" },
    { id: "1_286", english: "where", hebrew: "המקום שבו" },
    { id: "1_287", english: "whereas", hebrew: "ואילו / בעוד ש-" },
    { id: "1_288", english: "wherever", hebrew: "בכל מקום ש- / לאן ש-" },
    { id: "1_289", english: "whether... or…", hebrew: "בין אם... ובין אם..." },
    { id: "1_290", english: "which", hebrew: "איזה / אשר / ש-" },
    { id: "1_291", english: "which", hebrew: "הדבר ש-" },
    { id: "1_292", english: "while", hebrew: "בזמן ש- / בעוד ש- / למרות ש-" },
    { id: "1_293", english: "while", hebrew: "פרק זמן" },
    { id: "1_294", english: "who", hebrew: "מי / אשר / ש- (לאנשים)" },
    { id: "1_295", english: "whom", hebrew: "אותו / למי / אשר (מושא לאנשים)" },
    { id: "1_296", english: "whose", hebrew: "של מי / אשר שלו" },
    { id: "1_297", english: "why", hebrew: "למה / מדוע" },
    { id: "1_298", english: "with", hebrew: "עם / באמצעות" },
    { id: "1_299", english: "within", hebrew: "בתוך / במסגרת (זמן/מקום)" },
    { id: "1_300", english: "without", hebrew: "בלי / ללא" },
    { id: "1_301", english: "yet", hebrew: "עדיין (בשאלה/שלילה)" },
    { id: "1_302", english: "yet", hebrew: "אולם / עם זאת" }
  ],
"2": [
    { id: "2_1", english: "ability", hebrew: "יכולת" },
    { id: "2_2", english: "able", hebrew: "מסוגל" },
    { id: "2_3", english: "accept", hebrew: "לקבל / להסכים" },
    { id: "2_4", english: "acceptable", hebrew: "קביל / מקובל" },
    { id: "2_5", english: "acceptance", hebrew: "קבלה / הסכמה" },
    { id: "2_6", english: "accident", hebrew: "תאונה" },
    { id: "2_7", english: "achieve", hebrew: "להשיג / להגיע להישג" },
    { id: "2_8", english: "activate", hebrew: "להפעיל" },
    { id: "2_9", english: "active", hebrew: "פעיל" },
    { id: "2_10", english: "actor", hebrew: "שחקן" },
    { id: "2_11", english: "actual", hebrew: "ממשי / בפועל" },
    { id: "2_12", english: "actually", hebrew: "בעצם / למעשה" },
    { id: "2_13", english: "addition", hebrew: "תוספת / חיבור" },
    { id: "2_14", english: "address", hebrew: "כתובת / לנאום / לפנות אל" },
    { id: "2_15", english: "adjust", hebrew: "להתאים / לכוונן / להתרגל" },
    { id: "2_16", english: "afford", hebrew: "להרשות לעצמו כספית" },
    { id: "2_17", english: "afraid", hebrew: "מפוחד / חושש" },
    { id: "2_18", english: "agree", hebrew: "להסכים" },
    { id: "2_19", english: "agreement", hebrew: "הסכם / קבוצה" },
    { id: "2_20", english: "aim", hebrew: "מטרה / לכוון" },
    { id: "2_21", english: "alarm", hebrew: "אזעקה / להבהיל" },
    { id: "2_22", english: "alive", hebrew: "חי / בחיים" },
    { id: "2_23", english: "almost", hebrew: "כמעט" },
    { id: "2_24", english: "alone", hebrew: "לבד" },
    { id: "2_25", english: "alternate", hebrew: "לסירוגין / חלופי" },
    { id: "2_26", english: "altogether", hebrew: "לחלוטין / סך הכל" },
    { id: "2_27", english: "ambassador", hebrew: "שגריר" },
    { id: "2_28", english: "ambiguous", hebrew: "מעורפל / דו-משמעי" },
    { id: "2_29", english: "amount", hebrew: "כמות / סכום" },
    { id: "2_30", english: "anger", hebrew: "כעס / לכעוס" },
    { id: "2_31", english: "angry", hebrew: "כועס" },
    { id: "2_32", english: "animal", hebrew: "חיה / בעל חיים" },
    { id: "2_33", english: "another", hebrew: "אחר / נוסף / עוד אחד" },
    { id: "2_34", english: "answer", hebrew: "תשובה / לענות" },
    { id: "2_35", english: "apart", hebrew: "בנפרד / לחוד" },
    { id: "2_36", english: "apology", hebrew: "התנצלות" },
    { id: "2_37", english: "appear", hebrew: "להופיע / להיראות" },
    { id: "2_38", english: "appearance", hebrew: "הופעה / מראה חיצוני" },
    { id: "2_39", english: "appropriate", hebrew: "מתאים / הולם" },
    { id: "2_40", english: "approve", hebrew: "לאשר / להסכים ל-" },
    { id: "2_41", english: "architect", hebrew: "אדריכל" },
    { id: "2_42", english: "architecture", hebrew: "אדריכלות" },
    { id: "2_43", english: "area", hebrew: "אזור / שטח" },
    { id: "2_44", english: "argue", hebrew: "להתווכח / לטעון" },
    { id: "2_45", english: "argument", hebrew: "טיעון / ויכוח" },
    { id: "2_46", english: "aristocrat", hebrew: "אריסטוקרט / בן אצולה" },
    { id: "2_47", english: "arm", hebrew: "זרוע / לחמש בנשק" },
    { id: "2_48", english: "army", hebrew: "צבא" },
    { id: "2_49", english: "around", hebrew: "מסביב / בערך" },
    { id: "2_50", english: "arrange", hebrew: "לסדר / לארגן" },
    { id: "2_51", english: "arrest", hebrew: "לעצור / מעצר" },
    { id: "2_52", english: "arrive", hebrew: "להגיע" },
    { id: "2_53", english: "art", hebrew: "אמנות" },
    { id: "2_54", english: "article", hebrew: "מאמר / כתבה / פריט" },
    { id: "2_55", english: "articulate", hebrew: "רהוט / להביע ברור" },
    { id: "2_56", english: "artist", hebrew: "אמן" },
    { id: "2_57", english: "artistic", hebrew: "אמנותי" },
    { id: "2_58", english: "as far as", hebrew: "במידת ה- / ככל ש-" },
    { id: "2_59", english: "as proof of", hebrew: "כהוכחה ל-" },
    { id: "2_60", english: "ask", hebrew: "לבקש / לשאול" },
    { id: "2_61", english: "asked for", hebrew: "ביקש / דרש" },
    { id: "2_62", english: "associate", hebrew: "לקשר / לשייך" },
    { id: "2_63", english: "association", hebrew: "איגוד / אסוציאציה" },
    { id: "2_64", english: "assume", hebrew: "להניח / לשער" },
    { id: "2_65", english: "assumption", hebrew: "הנחה / משער" },
    { id: "2_66", english: "at least", hebrew: "לכל הפחות / לפחות" },
    { id: "2_67", english: "athlete", hebrew: "ספורטאי / אתלט" },
    { id: "2_68", english: "attach", hebrew: "לצרף / לחבר" },
    { id: "2_69", english: "attack", hebrew: "להתקיף / התקפה" },
    { id: "2_70", english: "attempt", hebrew: "לנסות / ניסיון" },
    { id: "2_71", english: "attitude", hebrew: "גישה / יחס" },
    { id: "2_72", english: "attract", hebrew: "למשוך / למגנט" },
    { id: "2_73", english: "attraction", hebrew: "אטרקציה / משיכה" },
    { id: "2_74", english: "attractive", hebrew: "מושך / אטרקטיבי" },
    { id: "2_75", english: "audience", hebrew: "קהל צופים" },
    { id: "2_76", english: "authentic", hebrew: "אותנטי / מקורי" },
    { id: "2_77", english: "availability", hebrew: "זמינות" },
    { id: "2_78", english: "available", hebrew: "זמין" },
    { id: "2_79", english: "average", hebrew: "ממוצע" },
    { id: "2_80", english: "avoid", hebrew: "להימנע מ-" },
    { id: "2_81", english: "awake", hebrew: "ער / להתעורר" },
    { id: "2_82", english: "bacteria", hebrew: "חיידקים" },
    { id: "2_83", english: "badly", hebrew: "קשות / בצורה רעה" },
    { id: "2_84", english: "baker", hebrew: "אופה" },
    { id: "2_85", english: "band", hebrew: "להקה / רצועה" },
    { id: "2_86", english: "barely", hebrew: "בקושי" },
    { id: "2_87", english: "base", hebrew: "בסיס / לבסס" },
    { id: "2_88", english: "bat", hebrew: "עטלף / מחבט" },
    { id: "2_89", english: "bath", hebrew: "אמבטיה / לרחוץ" },
    { id: "2_90", english: "battle", hebrew: "קרב / להילחם" },
    { id: "2_91", english: "beach", hebrew: "חוף ים" },
    { id: "2_92", english: "bear", hebrew: "דוב / לשאת / לסבול" },
    { id: "2_93", english: "beauty", hebrew: "יופי" },
    { id: "2_94", english: "bedroom", hebrew: "חדר שינה" },
    { id: "2_95", english: "begin/an/un", hebrew: "להתחיל (began/begun)" },
    { id: "2_96", english: "beginning", hebrew: "התחלה" },
    { id: "2_97", english: "belong", hebrew: "שייך ל-" },
    { id: "2_98", english: "best", hebrew: "הכי טוב / מיטב" },
    { id: "2_99", english: "best-seller", hebrew: "רב-מכר" },
    { id: "2_100", english: "better", hebrew: "טוב יותר" },
    { id: "2_101", english: "bicycle", hebrew: "אופניים" },
    { id: "2_102", english: "birth", hebrew: "לידה" },
    { id: "2_103", english: "bite", hebrew: "לנשוך / נשיכה" },
    { id: "2_104", english: "bizarre", hebrew: "מוזר / חריג" },
    { id: "2_105", english: "blind", hebrew: "עיוור" },
    { id: "2_106", english: "block", hebrew: "מחסום / לחסום / גוש" },
    { id: "2_107", english: "blood", hebrew: "דם" },
    { id: "2_108", english: "blood vessel", hebrew: "כלי דם" },
    { id: "2_109", english: "blow, blew", hebrew: "לנשוף / מכה / לנשב" },
    { id: "2_110", english: "boat", hebrew: "סירה" },
    { id: "2_111", english: "body", hebrew: "גוף" },
    { id: "2_112", english: "bone", hebrew: "עצם" },
    { id: "2_113", english: "border", hebrew: "גבול / לתחום" },
    { id: "2_114", english: "boring", hebrew: "משעמם" },
    { id: "2_115", english: "bottle", hebrew: "בקבוק" },
    { id: "2_116", english: "bottom", hebrew: "תחתית / קרקעית / חלק תחתון" },
    { id: "2_117", english: "bought", hebrew: "קנה (עבר של buy)" },
    { id: "2_118", english: "brain", hebrew: "מוח" },
    { id: "2_119", english: "brainwash", hebrew: "שטיפת מוח" },
    { id: "2_120", english: "brave", hebrew: "אמיץ" },
    { id: "2_121", english: "bread", hebrew: "לחם" },
    { id: "2_122", english: "break", hebrew: "לשבור / הפסקה" },
    { id: "2_123", english: "breathe", hebrew: "לנשום" },
    { id: "2_124", english: "bridge", hebrew: "גשר" },
    { id: "2_125", english: "broad", hebrew: "רחב / מקיף" },
    { id: "2_126", english: "budget", hebrew: "תקציב" },
    { id: "2_127", english: "build", hebrew: "לבנות / מבנה גוף" },
    { id: "2_128", english: "building", hebrew: "בניין / מבנה" },
    { id: "2_129", english: "built", hebrew: "בנה / בנוי" },
    { id: "2_130", english: "bullet", hebrew: "קליע / כדור רובה" },
    { id: "2_131", english: "by", hebrew: "על ידי / ליד / עד זמן מסוים" },
    { id: "2_132", english: "call", hebrew: "להתקשר / לקרוא / שיחה" },
    { id: "2_133", english: "camera", hebrew: "מצלמה" },
    { id: "2_134", english: "care", hebrew: "דאגה / לאכפת / טיפול" },
    { id: "2_135", english: "carefully", hebrew: "בזהירות / בתשומת לב" },
    { id: "2_136", english: "careless", hebrew: "רשלני / לא זהיר" },
    { id: "2_137", english: "carry", hebrew: "לשאת / לסחוב" },
    { id: "2_138", english: "catalogue", hebrew: "קטלוג" },
    { id: "2_139", english: "catch, caught", hebrew: "לתפוס (caught)" },
    { id: "2_140", english: "cause", hebrew: "סיבה / לגרום ל-" },
    { id: "2_141", english: "cell", hebrew: "תא (בגוף/כלא/טלפון)" },
    { id: "2_142", english: "center", hebrew: "מרכז" },
    { id: "2_143", english: "central", hebrew: "מרכזי" },
    { id: "2_144", english: "challenge", hebrew: "אתגר / לאתגר" },
    { id: "2_145", english: "chance", hebrew: "סיכוי / הזדמנות / מקריות" },
    { id: "2_146", english: "change", hebrew: "שינוי / לשנות / עודף כסף" },
    { id: "2_147", english: "characterize", hebrew: "לאפיין" },
    { id: "2_148", english: "cheap", hebrew: "זול" },
    { id: "2_149", english: "check", hebrew: "לבדוק / בדיקה / צ'ק" },
    { id: "2_150", english: "child", hebrew: "ילד" },
    { id: "2_151", english: "childhood", hebrew: "ילדות" },
    { id: "2_152", english: "children", hebrew: "ילדים" },
    { id: "2_153", english: "circle", hebrew: "עיגול / להקיף בעיגול" },
    { id: "2_154", english: "clean", hebrew: "נקי / לנקות" },
    { id: "2_155", english: "clever", hebrew: "חכם / פיקח" },
    { id: "2_156", english: "climb", hebrew: "לטפס / טיפוס" },
    { id: "2_157", english: "clock", hebrew: "שעון קיר" },
    { id: "2_158", english: "close", hebrew: "לסגור / קרוב" },
    { id: "2_159", english: "cloth", hebrew: "בד / מטלית" },
    { id: "2_160", english: "coach", hebrew: "מאמן / כרכרה" },
    { id: "2_161", english: "code", hebrew: "קוד" },
    { id: "2_162", english: "coexist", hebrew: "לחיות בדו-קיום" },
    { id: "2_163", english: "coin", hebrew: "מטבע" },
    { id: "2_164", english: "cold", hebrew: "קר / צינון" },
    { id: "2_165", english: "colonial", hebrew: "קולוניאלי" },
    { id: "2_166", english: "color", hebrew: "צבע / לצבוע" },
    { id: "2_167", english: "complain", hebrew: "להתלונן" },
    { id: "2_168", english: "complete", hebrew: "שלם / להשלים / לסיים" },
    { id: "2_169", english: "consist", hebrew: "להיות מורכב מ-" },
    { id: "2_170", english: "contact", hebrew: "קשר / ליצור קשר" },
    { id: "2_171", english: "continue", hebrew: "להמשיך" },
    { id: "2_172", english: "continuity", hebrew: "המשכיות / רצף" },
    { id: "2_173", english: "continuous", hebrew: "רציף / מתמשך" },
    { id: "2_174", english: "control", hebrew: "שליטה / לשלוט" },
    { id: "2_175", english: "cool", hebrew: "קריר / קול ומגניב" },
    { id: "2_176", english: "copies", hebrew: "עותקים" },
    { id: "2_177", english: "copy", hebrew: "עותק / להעתיק" },
    { id: "2_178", english: "corner", hebrew: "פינה" },
    { id: "2_179", english: "correct", hebrew: "נכון / לתקן" },
    { id: "2_180", english: "cost", hebrew: "עלות / לעלות מחיר" },
    { id: "2_181", english: "costly", hebrew: "יקר ערך / יקר" },
    { id: "2_182", english: "count", hebrew: "לספור / להחשיב" },
    { id: "2_183", english: "country", hebrew: "מדינה / אזור כפרי" },
    { id: "2_184", english: "cover", hebrew: "לכסות / כיסוי / עטיפה" },
    { id: "2_185", english: "cow", hebrew: "פרה" },
    { id: "2_186", english: "culture", hebrew: "תרבות" },
    { id: "2_187", english: "dance", hebrew: "לרקוד / ריקוד" },
    { id: "2_188", english: "danger", hebrew: "סכנה" },
    { id: "2_189", english: "dangerous", hebrew: "מסוכן" },
    { id: "2_190", english: "daughter", hebrew: "בת (של ההורים)" },
    { id: "2_191", english: "death", hebrew: "מוות" },
    { id: "2_192", english: "deep", hebrew: "עמוק" },
    { id: "2_193", english: "deeply", hebrew: "עמוקות" },
    { id: "2_194", english: "define", hebrew: "להגדיר" },
    { id: "2_195", english: "definite", hebrew: "החלטי / מוגדר / ברור" },
    { id: "2_196", english: "delete", hebrew: "למחוק" },
    { id: "2_197", english: "desert", hebrew: "מדבר / לנטוש" },
    { id: "2_198", english: "devastate", hebrew: "להחריב / להרוס לחלוטין" },
    { id: "2_199", english: "die", hebrew: "למות" },
    { id: "2_200", english: "die (dice)", hebrew: "קובית משחק" },
    { id: "2_201", english: "difficult", hebrew: "קשה / מורכב" },
    { id: "2_202", english: "dirty", hebrew: "מלוכלך" },
    { id: "2_203", english: "diverse", hebrew: "מגוון / שונה" },
    { id: "2_204", english: "done", hebrew: "עשוי / גמור" },
    { id: "2_205", english: "dream", hebrew: "חלום / לחלום" },
    { id: "2_206", english: "drink", hebrew: "לשתות / משקה" },
    { id: "2_207", english: "drug", hebrew: "תרופה / סם" },
    { id: "2_208", english: "due", hebrew: "חבוי / צפוי / עקב (due to)" },
    { id: "2_209", english: "early", hebrew: "מוקדם" },
    { id: "2_210", english: "earth", hebrew: "אדמה / עפר" },
    { id: "2_211", english: "Earth", hebrew: "כדור הארץ" },
    { id: "2_212", english: "earthquake", hebrew: "רעידת אדמה" },
    { id: "2_213", english: "educate", hebrew: "לחנך" },
    { id: "2_214", english: "education", hebrew: "חינוך" },
    { id: "2_215", english: "empty", hebrew: "ריק / לרוקן" },
    { id: "2_216", english: "enemy", hebrew: "אויב" },
    { id: "2_217", english: "energy", hebrew: "אנרגיה / מרץ" },
    { id: "2_218", english: "enjoy", hebrew: "ליהנות מ-" },
    { id: "2_219", english: "enjoyable", hebrew: "מהנה / נעים" },
    { id: "2_220", english: "enter", hebrew: "להיכנס / להזין נתונים" },
    { id: "2_221", english: "error", hebrew: "שגיאה / טעות" },
    { id: "2_222", english: "escape", hebrew: "לברוח / בריחה" },
    { id: "2_223", english: "evening", hebrew: "ערב" },
    { id: "2_224", english: "event", hebrew: "אירוע" },
    { id: "2_225", english: "exact", hebrew: "מדויק" },
    { id: "2_226", english: "exactly", hebrew: "בדיוק" },
    { id: "2_227", english: "example", hebrew: "דוגמה" },
    { id: "2_228", english: "excessive", hebrew: "מופרז / מוגזם" },
    { id: "2_229", english: "expert", hebrew: "מומחה" },
    { id: "2_230", english: "extinct", hebrew: "נכחד" },
    { id: "2_231", english: "fact", hebrew: "עובדה" },
    { id: "2_232", english: "false", hebrew: "שקרי / שגויה" },
    { id: "2_233", english: "farm", hebrew: "חווה / לטפח משק" },
    { id: "2_234", english: "farmer", hebrew: "חקלאי" },
    { id: "2_235", english: "father", hebrew: "אבא" },
    { id: "2_236", english: "fear", hebrew: "פחד / לפחד" },
    { id: "2_237", english: "feel", hebrew: "להרגיש / תחושה" },
    { id: "2_238", english: "feeling", hebrew: "הרגשה / רגש" },
    { id: "2_239", english: "few", hebrew: "מעט (ספיר)" },
    { id: "2_240", english: "field", hebrew: "שדה / תחום עיסוק" },
    { id: "2_241", english: "find", hebrew: "למצוא" },
    { id: "2_242", english: "findings", hebrew: "ממצאים (מחקר)" },
    { id: "2_243", english: "finger", hebrew: "אצבע ביד" },
    { id: "2_244", english: "fire", hebrew: "אש / לירות / לפטר" },
    { id: "2_245", english: "fix", hebrew: "לתקן / לקבוע" },
    { id: "2_246", english: "flower", hebrew: "פרח" },
    { id: "2_247", english: "forget", hebrew: "לשכוח" },
    { id: "2_248", english: "friend", hebrew: "חבר" },
    { id: "2_249", english: "friendly", hebrew: "ידידותי" },
    { id: "2_250", english: "friendship", hebrew: "חברות / ידידות" },
    { id: "2_251", english: "front", hebrew: "חזית / קדמי" },
    { id: "2_252", english: "full", hebrew: "מלא" },
    { id: "2_253", english: "gain", hebrew: "להרוויח / להשיג / רווח" },
    { id: "2_254", english: "glad", hebrew: "שמח / מרוצה" },
    { id: "2_255", english: "gradual", hebrew: "הדרגתי" },
    { id: "2_256", english: "great", hebrew: "נהדר / גדול" },
    { id: "2_257", english: "half", hebrew: "חצי" },
    { id: "2_258", english: "hand", hebrew: "יד / למסור" },
    { id: "2_259", english: "hear", hebrew: "לשמוע" },
    { id: "2_260", english: "hearsay", hebrew: "שמועה / משמועה" },
    { id: "2_261", english: "heat", hebrew: "חום / לחמם" },
    { id: "2_262", english: "hero", hebrew: "גיבור" },
    { id: "2_263", english: "horse", hebrew: "סוס" },
    { id: "2_264", english: "hot", hebrew: "חם / חריף / לוהט" },
    { id: "2_265", english: "house", hebrew: "בית / לאחסן / לשכן" },
    { id: "2_266", english: "impartial", hebrew: "בלתי משוחד / ניטרלי" },
    { id: "2_267", english: "inconsistent", hebrew: "לא עקבי / סותר" },
    { id: "2_268", english: "insert", hebrew: "להכניס / להחדיר" },
    { id: "2_269", english: "jump", hebrew: "לקפוץ / קפיצה" },
    { id: "2_270", english: "just", hebrew: "רק / צודק / כרגע" },
    { id: "2_271", english: "kill", hebrew: "להרוג" },
    { id: "2_272", english: "king", hebrew: "מלך" },
    { id: "2_273", english: "kingdom", hebrew: "ממלכה" },
    { id: "2_274", english: "kitchen", hebrew: "מטבח" },
    { id: "2_275", english: "last", hebrew: "אחרון / להחזיק מעמד" },
    { id: "2_276", english: "late", hebrew: "מאוחר / המנוח" },
    { id: "2_277", english: "light", hebrew: "אור / קל / להדליק" },
    { id: "2_278", english: "like", hebrew: "לאהוב / כמו" },
    { id: "2_279", english: "list", hebrew: "רשימה / לרשום" },
    { id: "2_280", english: "lock", hebrew: "מנעול / לנעול" },
    { id: "2_281", english: "logic", hebrew: "היגיון" },
    { id: "2_282", english: "main", hebrew: "עיקרי / מרכזי" },
    { id: "2_283", english: "map", hebrew: "מפה / למפות" },
    { id: "2_284", english: "mark", hebrew: "סימן / ציון / לסמן" },
    { id: "2_285", english: "maybe", hebrew: "אולי" },
    { id: "2_286", english: "meeting", hebrew: "פגישה / אסיפה" },
    { id: "2_287", english: "member", hebrew: "חבר בארגון" },
    { id: "2_288", english: "milk", hebrew: "חלב / לחלוב" },
    { id: "2_289", english: "mistake", hebrew: "טעות / לטעות" },
    { id: "2_290", english: "mistaken", hebrew: "טועה / מוטעה" },
    { id: "2_291", english: "money", hebrew: "כסף" },
    { id: "2_292", english: "move", hebrew: "לזוז / להניע / צעד" },
    { id: "2_293", english: "movement", hebrew: "תנועה / מגמה" },
    { id: "2_294", english: "must", hebrew: "חייב / חובה" },
    { id: "2_295", english: "number", hebrew: "מספר / למספר" },
    { id: "2_296", english: "once", hebrew: "פעם אחת / ברגע ש-" },
    { id: "2_297", english: "open", hebrew: "פתוח / לפתוח" },
    { id: "2_298", english: "over", hebrew: "מעל / נגמר" },
    { id: "2_299", english: "paragraph", hebrew: "פסקה" },
    { id: "2_300", english: "pay", hebrew: "לשלם / שכר" },
    { id: "2_301", english: "peace", hebrew: "שלום / שקט" },
    { id: "2_302", english: "peaceful", hebrew: "שלו / פסטורלי" },
    { id: "2_303", english: "pilot", hebrew: "טייס / ניסיוני" },
    { id: "2_304", english: "place", hebrew: "מקום / למקם" },
    { id: "2_305", english: "plan", hebrew: "תוכנית / לתכנן" },
    { id: "2_306", english: "plane", hebrew: "מטוס / מישור" },
    { id: "2_307", english: "president", hebrew: "נשיא / יו''ר" },
    { id: "2_308", english: "price", hebrew: "מחיר / לתמחר" },
    { id: "2_309", english: "primary", hebrew: "ראשוני / יסודי / עיקרי" },
    { id: "2_310", english: "problem", hebrew: "בעיה" },
    { id: "2_311", english: "program", hebrew: "תוכנית / לתכנת / לו''ז" },
    { id: "2_312", english: "queen", hebrew: "מלכה" },
    { id: "2_313", english: "question", hebrew: "שאלה / לערער / לחקור" },
    { id: "2_314", english: "quick", hebrew: "מהיר" },
    { id: "2_315", english: "rates", hebrew: "שיעורים / תעריפים / קצבים" },
    { id: "2_316", english: "rather", hebrew: "למדי / למעשה" },
    { id: "2_317", english: "react", hebrew: "להגיב" },
    { id: "2_318", english: "region", hebrew: "אזור / מחוז" },
    { id: "2_319", english: "register", hebrew: "להירשם / לוג" },
    { id: "2_320", english: "registration", hebrew: "הרשמה" },
    { id: "2_321", english: "reject", hebrew: "לדחות / לפסול" },
    { id: "2_322", english: "rest", hebrew: "מנוחה / לנוח / השאר" },
    { id: "2_323", english: "rich", hebrew: "עשיר" },
    { id: "2_324", english: "right", hebrew: "ימין / צדק / זכות" },
    { id: "2_325", english: "risk", hebrew: "סיכון / לסכן" },
    { id: "2_326", english: "river", hebrew: "נהר" },
    { id: "2_327", english: "road", hebrew: "כביש / דרך" },
    { id: "2_328", english: "safe", hebrew: "בתוח / כספת" },
    { id: "2_329", english: "safety", hebrew: "בטיחות" },
    { id: "2_330", english: "save", hebrew: "להציל / לשמור / לחסוך" },
    { id: "2_331", english: "scare", hebrew: "להבהיל / פחד" },
    { id: "2_332", english: "school", hebrew: "בית ספר / אסכולה" },
    { id: "2_333", english: "search", hebrew: "חיפוש / לחפש" },
    { id: "2_334", english: "select", hebrew: "לבחור / נבחר" },
    { id: "2_335", english: "sell", hebrew: "למכור" },
    { id: "2_336", english: "send", hebrew: "לשלוח" },
    { id: "2_337", english: "several", hebrew: "כמה / אחדים" },
    { id: "2_338", english: "short", hebrew: "קצר / נמוך" },
    { id: "2_339", english: "shortage", hebrew: "מחסור / גרעון" },
    { id: "2_340", english: "side", hebrew: "צד / דופן" },
    { id: "2_341", english: "sleep", hebrew: "לישון / להירדם" },
    { id: "2_342", english: "slow", hebrew: "איטי" },
    { id: "2_343", english: "slow down", hebrew: "להאט" },
    { id: "2_344", english: "so", hebrew: "אז / כל כך / לכן" },
    { id: "2_345", english: "space", hebrew: "חלל / מרחב / לרווח" },
    { id: "2_346", english: "speed", hebrew: "מהירות / למהר" },
    { id: "2_347", english: "start", hebrew: "להתחיל / זינוק" },
    { id: "2_348", english: "still", hebrew: "עדיין / שקט" },
    { id: "2_349", english: "stone", hebrew: "אבן" },
    { id: "2_350", english: "strong", hebrew: "חזק" },
    { id: "2_351", english: "stronghold", hebrew: "מעוז / מבצר" },
    { id: "2_352", english: "system", hebrew: "מערכת / שיטה / מנגנון" },
    { id: "2_353", english: "target", hebrew: "מטרה / יעד / לכוון" },
    { id: "2_354", english: "teach, taught", hebrew: "ללמד (taught)" },
    { id: "2_355", english: "think, thought", hebrew: "לחשוב / מחשבה (thought)" },
    { id: "2_356", english: "time", hebrew: "זמן / פעם / לתזמן" },
    { id: "2_357", english: "totally", hebrew: "לחלוטין / לגמרי" },
    { id: "2_358", english: "town", hebrew: "עיירה / עיר קטנה" },
    { id: "2_359", english: "understand", hebrew: "להבין" },
    { id: "2_360", english: "unusual", hebrew: "חריג / בלתי רגיל" },
    { id: "2_361", english: "use", hebrew: "להשתמש / שימוש / תועלת" },
    { id: "2_362", english: "useful", hebrew: "שימושי / יעיל" },
    { id: "2_363", english: "useless", hebrew: "חסר תועלת" },
    { id: "2_364", english: "usual", hebrew: "רגיל / סטנדרטי" },
    { id: "2_365", english: "valuable", hebrew: "יקר ערך" },
    { id: "2_366", english: "value", hebrew: "ערך / להעריך" },
    { id: "2_367", english: "view", hebrew: "נוף / השקפה / לראות" },
    { id: "2_368", english: "viewer", hebrew: "צופה במסך" },
    { id: "2_369", english: "visit", hebrew: "לבקר / ביקור" },
    { id: "2_370", english: "visitor", hebrew: "אורח / מבקר" },
    { id: "2_371", english: "voice", hebrew: "קול (דיבור)" },
    { id: "2_372", english: "wait", hebrew: "לחכות / המתנה" },
    { id: "2_373", english: "way", hebrew: "דרך / אופן / נתיב" },
    { id: "2_374", english: "weather", hebrew: "מזג אוויר" }
  ],
"3": [
    { id: "3_1", english: "abrupt", hebrew: "פתאומי / מפתיע" },
    { id: "3_2", english: "absolute", hebrew: "מוחלט / גמור" },
    { id: "3_3", english: "accessible", hebrew: "נגיש / זמין" },
    { id: "3_4", english: "accomplish", hebrew: "להשיג / לבצע" },
    { id: "3_5", english: "accomplished", hebrew: "מושלם / בעל הישגים" },
    { id: "3_6", english: "accomplishment", hebrew: "הישג" },
    { id: "3_7", english: "account", hebrew: "חשבון / דיווח / להחשיב" },
    { id: "3_8", english: "accuracy", hebrew: "דיוק" },
    { id: "3_9", english: "accurate", hebrew: "מדויק" },
    { id: "3_10", english: "activist", hebrew: "אקטיביסט / פעיל" },
    { id: "3_11", english: "adapt", hebrew: "להתאים / להסתגל / לעבד" },
    { id: "3_12", english: "administer", hebrew: "לנהל / לתת תרופה" },
    { id: "3_13", english: "administration", hebrew: "מנהל / הממשל" },
    { id: "3_14", english: "admit", hebrew: "להודות / לאפשר כניסה" },
    { id: "3_15", english: "adult", hebrew: "מבוגר" },
    { id: "3_16", english: "adulthood", hebrew: "בגרות" },
    { id: "3_17", english: "advance", hebrew: "להתקדם / מקדמה" },
    { id: "3_18", english: "advancement", hebrew: "התקדמות / קידום" },
    { id: "3_19", english: "advantage", hebrew: "יתרון" },
    { id: "3_20", english: "advice", hebrew: "עצה" },
    { id: "3_21", english: "advise", hebrew: "לייעץ" },
    { id: "3_22", english: "advisor", hebrew: "יועץ" },
    { id: "3_23", english: "aesthetic", hebrew: "אסתטי / יפה" },
    { id: "3_24", english: "allocate", hebrew: "להקצות / להקציב" },
    { id: "3_25", english: "announcement", hebrew: "הודעה / הכרזה" },
    { id: "3_26", english: "annually", hebrew: "מדי שנה" },
    { id: "3_27", english: "appoint", hebrew: "למנות לתפקיד" },
    { id: "3_28", english: "approach", hebrew: "גישה / להתקרב" },
    { id: "3_29", english: "approximately", hebrew: "בערך / בקירוב" },
    { id: "3_30", english: "astronomy", hebrew: "אסטרונומיה" },
    { id: "3_31", english: "attention", hebrew: "תשומת לב" },
    { id: "3_32", english: "attribute", hebrew: "תכונה / לייחס ל-" },
    { id: "3_33", english: "aware", hebrew: "מודע" },
    { id: "3_34", english: "balance", hebrew: "איזון / יתרה בחשבון" },
    { id: "3_35", english: "ban", hebrew: "חרם / לאסור" },
    { id: "3_36", english: "belief", hebrew: "אמונה" },
    { id: "3_37", english: "bend", hebrew: "לכופף / להתכופף" },
    { id: "3_38", english: "beware", hebrew: "להיזהר" },
    { id: "3_39", english: "borrow", hebrew: "לשאול / להלוות" },
    { id: "3_40", english: "brief", hebrew: "קצר / תמציתי" },
    { id: "3_41", english: "briefly", hebrew: "בקיצור / בקצרה" },
    { id: "3_42", english: "bright", hebrew: "בהיר / חכם" },
    { id: "3_43", english: "by no means", hebrew: "בשום אופן לא" },
    { id: "3_44", english: "by now", hebrew: "כבר עכשיו / עד עכשיו" },
    { id: "3_45", english: "capable", hebrew: "מסוגל / מוכשר" },
    { id: "3_46", english: "capacity", hebrew: "קיבולת / יכולת / תפקיד" },
    { id: "3_47", english: "capital", hebrew: "עיר בירה / הון / אות גדולה" },
    { id: "3_48", english: "capital punishment", hebrew: "עונש מוות" },
    { id: "3_49", english: "capitalize", hebrew: "להפיק תועלת / לכתוב באות גדולה" },
    { id: "3_50", english: "certain", hebrew: "בטוח / ודאי / מסוים" },
    { id: "3_51", english: "certainty", hebrew: "ודאות" },
    { id: "3_52", english: "character", hebrew: "אופי / דמות / אות תו" },
    { id: "3_53", english: "characteristic", hebrew: "מאפיין / אופייני" },
    { id: "3_54", english: "choice", hebrew: "בחירה" },
    { id: "3_55", english: "choose", hebrew: "לבחור" },
    { id: "3_56", english: "circumstance", hebrew: "נסיבה / תנאי" },
    { id: "3_57", english: "civil", hebrew: "אזרחי / מנומס" },
    { id: "3_58", english: "class", hebrew: "מעמד / כיתה / סוג" },
    { id: "3_59", english: "classify", hebrew: "לסווג" },
    { id: "3_60", english: "colony", hebrew: "מושבה" },
    { id: "3_61", english: "combine", hebrew: "לשלב / לאחד" },
    { id: "3_62", english: "common", hebrew: "משותף / נפוץ" },
    { id: "3_63", english: "communal", hebrew: "שיתופי / קהילתי" },
    { id: "3_64", english: "communicate", hebrew: "לתקשר" },
    { id: "3_65", english: "community", hebrew: "קהילה" },
    { id: "3_66", english: "company", hebrew: "חברה עסקית / חברה אנשים" },
    { id: "3_67", english: "comparable", hebrew: "בר השוואה / דומה" },
    { id: "3_68", english: "compare", hebrew: "להשוות" },
    { id: "3_69", english: "comparison", hebrew: "השוואה" },
    { id: "3_70", english: "comprehend", hebrew: "להבין / לתפוס" },
    { id: "3_71", english: "comprehension", hebrew: "הבנה" },
    { id: "3_72", english: "concentrate", hebrew: "להתרכז / לרכז" },
    { id: "3_73", english: "conclude", hebrew: "להסיק / לסיים / לסכם" },
    { id: "3_74", english: "conclusion", hebrew: "מסקנה / סיום" },
    { id: "3_75", english: "conclusively", hebrew: "באופן חד משמעי" },
    { id: "3_76", english: "confirm", hebrew: "לאשר / לאמת" },
    { id: "3_77", english: "continuation", hebrew: "המשך" },
    { id: "3_78", english: "cooperation", hebrew: "שיתוף פעולה" },
    { id: "3_79", english: "core", hebrew: "ליבה / מרכז" },
    { id: "3_80", english: "crisis", hebrew: "משבר" },
    { id: "3_81", english: "cure", hebrew: "ריפוי / תרופה" },
    { id: "3_82", english: "decide", hebrew: "להחליט" },
    { id: "3_83", english: "decline", hebrew: "להידרדר / ירידה / לסרב" },
    { id: "3_84", english: "decrease", hebrew: "להפחית / הפחתה / צמצום" },
    { id: "3_85", english: "deduce", hebrew: "להסיק (מסקנה)" },
    { id: "3_86", english: "demand", hebrew: "דרישה / לדרוש / ביקוש" },
    { id: "3_87", english: "deny", hebrew: "להכחיש / למנוע / לסרב" },
    { id: "3_88", english: "depart", hebrew: "לעזוב / לצאת לדרך" },
    { id: "3_89", english: "derive", hebrew: "להפיק / לנבוע מ-" },
    { id: "3_90", english: "descend", hebrew: "לרדת / לשקוע" },
    { id: "3_91", english: "descendent", hebrew: "צאצא" },
    { id: "3_92", english: "deserve", hebrew: "להיות ראוי ל-" },
    { id: "3_93", english: "destiny", hebrew: "גורל" },
    { id: "3_94", english: "devote", hebrew: "להקדיש זמן" },
    { id: "3_95", english: "direct", hebrew: "ישיר / לכוון / לביים" },
    { id: "3_96", english: "direction", hebrew: "כיוון / הנחיה" },
    { id: "3_97", english: "disadvantage", hebrew: "חיסרון" },
    { id: "3_98", english: "disclose", hebrew: "לחשוף / לגלות" },
    { id: "3_99", english: "discover", hebrew: "לגלות" },
    { id: "3_100", english: "discoveries", hebrew: "תגליות" },
    { id: "3_101", english: "discuss", hebrew: "לדון / לשוחח" },
    { id: "3_102", english: "disprove", hebrew: "להפריך / להוכיח שאינו נכון" },
    { id: "3_103", english: "distinct", hebrew: "מובחן / ברור / נפרד" },
    { id: "3_104", english: "distress", hebrew: "מצוקה / סבל" },
    { id: "3_105", english: "diverge", hebrew: "להתפצל / לסטות" },
    { id: "3_106", english: "diversity", hebrew: "גיוון / שוני" },
    { id: "3_107", english: "divide", hebrew: "לחלק / לפצל" },
    { id: "3_108", english: "doubt", hebrew: "ספק / להטיל ספק" },
    { id: "3_109", english: "edit", hebrew: "לערוך" },
    { id: "3_110", english: "edition", hebrew: "מהדורה" },
    { id: "3_111", english: "editor", hebrew: "עורך" },
    { id: "3_112", english: "emperor", hebrew: "קיסר" },
    { id: "3_113", english: "empire", hebrew: "אימפריה" },
    { id: "3_114", english: "enable", hebrew: "לאפשר" },
    { id: "3_115", english: "enormous", hebrew: "עצום / ענק" },
    { id: "3_116", english: "enough", hebrew: "מספיק" },
    { id: "3_117", english: "era", hebrew: "עידן / תקופה" },
    { id: "3_118", english: "essential", hebrew: "חיוני / מהותי" },
    { id: "3_119", english: "evaluate", hebrew: "להעריך" },
    { id: "3_120", english: "evaluation", hebrew: "הערכה" },
    { id: "3_121", english: "even", hebrew: "אפילו / זוגי / יציב" },
    { id: "3_122", english: "evenly", hebrew: "באופן שווה / חלקה" },
    { id: "3_123", english: "except for", hebrew: "מלבד / חוץ מ-" },
    { id: "3_124", english: "exercise", hebrew: "תרגיל / להתעמל / להפעיל סמכות" },
    { id: "3_125", english: "expect", hebrew: "לצפות ל-" },
    { id: "3_126", english: "expectations", hebrew: "ציפיות" },
    { id: "3_127", english: "explain", hebrew: "להסביר" },
    { id: "3_128", english: "explanation", hebrew: "הסבר" },
    { id: "3_129", english: "express", hebrew: "להביע / מהיר" },
    { id: "3_130", english: "expression", hebrew: "ביטוי / הבעה" },
    { id: "3_131", english: "extreme", hebrew: "קיצוני" },
    { id: "3_132", english: "face", hebrew: "פנים / להתמודד" },
    { id: "3_133", english: "facial", hebrew: "של הפנים" },
    { id: "3_134", english: "financial", hebrew: "פיננסי / כספי" },
    { id: "3_135", english: "forbid", hebrew: "לאסור" },
    { id: "3_136", english: "form", hebrew: "צורה / טופס / ליצור / סוג" },
    { id: "3_137", english: "formal", hebrew: "רשמי" },
    { id: "3_138", english: "forth", hebrew: "הלאה / קדימה" },
    { id: "3_139", english: "general", hebrew: "כללי / גנרל" },
    { id: "3_140", english: "generally", hebrew: "בדרך כלל" },
    { id: "3_141", english: "gross", hebrew: "גס / מגעיל / ברוטו" },
    { id: "3_142", english: "growth", hebrew: "צמיחה / גידול" },
    { id: "3_143", english: "habit", hebrew: "הרגיל / מנהג" },
    { id: "3_144", english: "habitat", hebrew: "סביבת מחיה טבעית" },
    { id: "3_145", english: "health", hebrew: "בריאות" },
    { id: "3_146", english: "heavily", hebrew: "בכבדות / קשות" },
    { id: "3_147", english: "heavy", hebrew: "כבד" },
    { id: "3_148", english: "hope", hebrew: "תקווה / לקוות" },
    { id: "3_149", english: "human", hebrew: "אנושי / בן אדם" },
    { id: "3_150", english: "identical", hebrew: "זהה לחלוטין" },
    { id: "3_151", english: "implicate", hebrew: "לערב / לסבך בפשע" },
    { id: "3_152", english: "implications", hebrew: "השלכות" },
    { id: "3_153", english: "importance", hebrew: "חשיבות" },
    { id: "3_154", english: "important", hebrew: "חשוב" },
    { id: "3_155", english: "inadequate", hebrew: "בלתי מספיק / לא הולם" },
    { id: "3_156", english: "income", hebrew: "הכנסה כספית" },
    { id: "3_157", english: "incomprehensible", hebrew: "בלתי מובן" },
    { id: "3_158", english: "indicate", hebrew: "להצביע על / להראות" },
    { id: "3_159", english: "indication", hebrew: "אינדיקציה / סימן" },
    { id: "3_160", english: "inhabit", hebrew: "לאכלס / לגור ב-" },
    { id: "3_161", english: "inhabitants", hebrew: "תושבים" },
    { id: "3_162", english: "initial", hebrew: "ראשוני / אות ראשונה" },
    { id: "3_163", english: "initiated", hebrew: "יזם / התחיל" },
    { id: "3_164", english: "international", hebrew: "בינלאומי" },
    { id: "3_165", english: "island", hebrew: "אי" },
    { id: "3_166", english: "isle", hebrew: "אי קטן" },
    { id: "3_167", english: "issue", hebrew: "נושא / להנפיק / גיליון עיתון" },
    { id: "3_168", english: "jewel", hebrew: "תכשיט / אבן חן" },
    { id: "3_169", english: "join", hebrew: "להצטרף / לחבר" },
    { id: "3_170", english: "joint", hebrew: "משותף / מפרק בגוף" },
    { id: "3_171", english: "judge", hebrew: "שופט / לשפוט" },
    { id: "3_172", english: "lack", hebrew: "מחסור / חוסר" },
    { id: "3_173", english: "language", hebrew: "שפה" },
    { id: "3_174", english: "large", hebrew: "גדול / רחב" },
    { id: "3_175", english: "largest", hebrew: "הכי גדול" },
    { id: "3_176", english: "law", hebrew: "חוק / משפט" },
    { id: "3_177", english: "lawyer", hebrew: "עורך דין" },
    { id: "3_178", english: "legal", hebrew: "חוקי / משפטי" },
    { id: "3_179", english: "legalize", hebrew: "להפוך לחוקי / לגליזציה" },
    { id: "3_180", english: "less", hebrew: "פחות" },
    { id: "3_181", english: "lethal", hebrew: "קטלני / ממית" },
    { id: "3_182", english: "level", hebrew: "רמה / לשטח / לפלס" },
    { id: "3_183", english: "likely", hebrew: "סביר להניח / צפוי" },
    { id: "3_184", english: "local", hebrew: "מקומי" },
    { id: "3_185", english: "locate", hebrew: "לאתר / למקם" },
    { id: "3_186", english: "malfunction", hebrew: "תקלה / שיבוש" },
    { id: "3_187", english: "massacre", hebrew: "טבח / לטבוח" },
    { id: "3_188", english: "medicine", hebrew: "תרופה / רפואה" },
    { id: "3_189", english: "medieval", hebrew: "של ימי הביניים" },
    { id: "3_190", english: "merchandise", hebrew: "סחורה" },
    { id: "3_191", english: "mere", hebrew: "רק / בלבד / ותו לא" },
    { id: "3_192", english: "merely", hebrew: "רק / בלבד" },
    { id: "3_193", english: "middle", hebrew: "אמצע / מרכז" },
    { id: "3_194", english: "mortal", hebrew: "בן תמותה / קטלני" },
    { id: "3_195", english: "mortality", hebrew: "תמותה" },
    { id: "3_196", english: "most", hebrew: "הכי / הרוב / מרבית" },
    { id: "3_197", english: "mutually", hebrew: "באופן הדדי" },
    { id: "3_198", english: "nation", hebrew: "אומה / מדינה" },
    { id: "3_199", english: "nationality", hebrew: "לאום / אזרחות" },
    { id: "3_200", english: "nationalize", hebrew: "להפוך ללאומי" },
    { id: "3_201", english: "native", hebrew: "בן המקום / יליד" },
    { id: "3_202", english: "natural", hebrew: "טבעי" },
    { id: "3_203", english: "nature", hebrew: "טבע / אופי המהות" },
    { id: "3_204", english: "need", hebrew: "צורך / להזדקק" },
    { id: "3_205", english: "negative", hebrew: "שלילי / תשליל" },
    { id: "3_206", english: "network", hebrew: "רשת" },
    { id: "3_207", english: "new", hebrew: "חדש" },
    { id: "3_208", english: "newscaster", hebrew: "מגיש חדשות" },
    { id: "3_209", english: "newspaper", hebrew: "עיתון" },
    { id: "3_210", english: "note", hebrew: "הערה / פתק / לשים לב" },
    { id: "3_211", english: "noted", hebrew: "מפורסם / ידוע לשבח" },
    { id: "3_212", english: "obviously", hebrew: "כמובן / באופן ברור" },
    { id: "3_213", english: "occasion", hebrew: "אירוע / הזדמנות" },
    { id: "3_214", english: "occasional", hebrew: "מקרי / מדי פעם" },
    { id: "3_215", english: "occasions", hebrew: "אירועים / מקרים" },
    { id: "3_216", english: "occur", hebrew: "התרחש / קרה" },
    { id: "3_217", english: "offer", hebrew: "הצעה / להציע" },
    { id: "3_218", english: "official", hebrew: "רשמי / פקיד" },
    { id: "3_219", english: "officiate", hebrew: "לנהל טקס / לכהן" },
    { id: "3_220", english: "oil", hebrew: "שמן / נפט" },
    { id: "3_221", english: "ongoing", hebrew: "מתמשך / מתנהל" },
    { id: "3_222", english: "option", hebrew: "אפשרות / אופציה" },
    { id: "3_223", english: "order", hebrew: "סדר / פקודה / להזמין" },
    { id: "3_224", english: "orderly", hebrew: "מסודר / מאורגן" },
    { id: "3_225", english: "orientation", hebrew: "אוריינטציה / התמצאות" },
    { id: "3_226", english: "origin", hebrew: "מקור / מוצא" },
    { id: "3_227", english: "original", hebrew: "מקורי / מקור" },
    { id: "3_228", english: "originality", hebrew: "מקוריות" },
    { id: "3_229", english: "originate", hebrew: "לנבוע / להיווצר" },
    { id: "3_230", english: "outcome", hebrew: "תוצאה" },
    { id: "3_231", english: "overcome", hebrew: "להתגבר על" },
    { id: "3_232", english: "part", hebrew: "חלק / להיפרד" },
    { id: "3_233", english: "partial", hebrew: "חלקי / משוחד" },
    { id: "3_234", english: "patient", hebrew: "סבלני / מטופל חולה" },
    { id: "3_235", english: "per", hebrew: "לכל / לכל יחידה" },
    { id: "3_236", english: "percent", hebrew: "אחוז" },
    { id: "3_237", english: "perfect", hebrew: "מושלם / לשכלל" },
    { id: "3_238", english: "pollution", hebrew: "זיהום" },
    { id: "3_239", english: "population", hebrew: "אוכלוסייה" },
    { id: "3_240", english: "possess", hebrew: "להחזיק בבעלותו / לשלוט" },
    { id: "3_241", english: "possession", hebrew: "רכוש / חזקה" },
    { id: "3_242", english: "precise", hebrew: "מדויק" },
    { id: "3_243", english: "precision", hebrew: "דיוק רב" },
    { id: "3_244", english: "presence", hebrew: "נוכחות" },
    { id: "3_245", english: "present", hebrew: "מתנה / הווה / להציג / להעלות" },
    { id: "3_246", english: "prime", hebrew: "ראשי / מובחר / ראשוני" },
    { id: "3_247", english: "primitive", hebrew: "פרימיטיבי / קדום" },
    { id: "3_248", english: "prior", hebrew: "קודם / מוקדם" },
    { id: "3_249", english: "priority", hebrew: "עדיפות / קדימות" },
    { id: "3_250", english: "progress", hebrew: "התקדמות / להתקדם" },
    { id: "3_251", english: "progressive", hebrew: "מתקדם" },
    { id: "3_252", english: "proper", hebrew: "הולם / תקין" },
    { id: "3_253", english: "properly", hebrew: "היטב / כמו שצריך" },
    { id: "3_254", english: "protect", hebrew: "להגן" },
    { id: "3_255", english: "provide", hebrew: "לספק / לפרנס" },
    { id: "3_256", english: "purpose", hebrew: "מטרה / תכלית" },
    { id: "3_257", english: "purposely", hebrew: "בכוונה" },
    { id: "3_258", english: "quiet", hebrew: "שקט / להשקיט" },
    { id: "3_259", english: "quite", hebrew: "די / לחלוטין" },
    { id: "3_260", english: "quote", hebrew: "ציטוט / לצטט" },
    { id: "3_261", english: "raise", hebrew: "להרים / לגדל / להעלות שכר" },
    { id: "3_262", english: "range", hebrew: "טווח / רכס / מגוון" },
    { id: "3_263", english: "rational", hebrew: "רציונלי" },
    { id: "3_264", english: "rationalize", hebrew: "להצדיק" },
    { id: "3_265", english: "reality", hebrew: "מציאות / ריאליטי" },
    { id: "3_266", english: "reason", hebrew: "סיבה / היגיון / להסביר" },
    { id: "3_267", english: "recession", hebrew: "מיתון כספי" },
    { id: "3_268", english: "recommend", hebrew: "להמליץ" },
    { id: "3_269", english: "recycle", hebrew: "למחזר" },
    { id: "3_270", english: "recycling", hebrew: "מיחזור" },
    { id: "3_271", english: "reduce", hebrew: "להפחית / לצמצם" },
    { id: "3_272", english: "refer", hebrew: "להתייחס / להפנות" },
    { id: "3_273", english: "reference", hebrew: "התייחסות / סימוכין" },
    { id: "3_274", english: "refuse", hebrew: "לסרב / פסולת אשפה" },
    { id: "3_275", english: "regime", hebrew: "משטר / שלטון" },
    { id: "3_276", english: "regulation", hebrew: "תקנה / רגולציה" },
    { id: "3_277", english: "reign", hebrew: "תקופת שלטון / למלוך" },
    { id: "3_278", english: "reigned", hebrew: "מלך / שלט" },
    { id: "3_279", english: "relative", hebrew: "קרוב משפחה / יחסי" },
    { id: "3_280", english: "relatively", hebrew: "יחסית" },
    { id: "3_281", english: "religion", hebrew: "דת" },
    { id: "3_282", english: "repeat", hebrew: "לחזור על / חזרה" },
    { id: "3_283", english: "repetition", hebrew: "חזרה / רפיטציה" },
    { id: "3_284", english: "reply", hebrew: "תשובה / לענות" },
    { id: "3_285", english: "research", hebrew: "מחקר / לחקור" },
    { id: "3_286", english: "resist", hebrew: "להתנגד / לעמוד בפני" },
    { id: "3_287", english: "resistance", hebrew: "התנגדות" },
    { id: "3_288", english: "resolve", hebrew: "לפתור בעיה / נחישות" },
    { id: "3_289", english: "result", hebrew: "תוצאה / לנבוע מ-" },
    { id: "3_290", english: "result in", hebrew: "להסתיים ב- / להוביל ל-" },
    { id: "3_291", english: "reveal", hebrew: "לחשוף / לגלות" },
    { id: "3_292", english: "review", hebrew: "ביקורת / סקירה / חזרה" },
    { id: "3_293", english: "rigid", hebrew: "נוקשה / קשיח" },
    { id: "3_294", english: "rise", hebrew: "לעלות / עלייה" },
    { id: "3_295", english: "rising", hebrew: "עולה / מרד התקוממות" },
    { id: "3_296", english: "rocket", hebrew: "רקטה / טיל / לנסוק" },
    { id: "3_297", english: "scene", hebrew: "סצנה / זירה / תפאורה" },
    { id: "3_298", english: "scenery", hebrew: "נוף / תפאורה" },
    { id: "3_299", english: "science", hebrew: "מדע" },
    { id: "3_300", english: "scientist", hebrew: "מדען" },
    { id: "3_301", english: "section", hebrew: "חלק / קטע / סעיף" },
    { id: "3_302", english: "seem", hebrew: "להידמות / להיראות ש-" },
    { id: "3_303", english: "sense", hebrew: "חוש / תחושה / משמעות" },
    { id: "3_304", english: "sensible", hebrew: "נבון / הגיוני" },
    { id: "3_305", english: "serious", hebrew: "רציני / חמור" },
    { id: "3_306", english: "shuttle", hebrew: "מעבורת / קו הסעות" },
    { id: "3_307", english: "sign", hebrew: "שלט / סימן / לחתום / אות" },
    { id: "3_308", english: "signal", hebrew: "אות / לאותת" },
    { id: "3_309", english: "similar", hebrew: "דומה" },
    { id: "3_310", english: "simple", hebrew: "פשוט" },
    { id: "3_311", english: "simplify", hebrew: "לפשט" },
    { id: "3_312", english: "simply", hebrew: "פשוט / בלבד" },
    { id: "3_313", english: "social", hebrew: "חברתי" },
    { id: "3_314", english: "spacious", hebrew: "מרווח / רחב ידיים" },
    { id: "3_315", english: "square", hebrew: "ריבוע / כיכר" },
    { id: "3_316", english: "stand", hebrew: "לעמוד / עמדה / דוכן" },
    { id: "3_317", english: "standardize", hebrew: "לתקנן" },
    { id: "3_318", english: "subject", hebrew: "נושא / נתין / נבדק / כפוף" },
    { id: "3_319", english: "subjective", hebrew: "סובייקטיבי" },
    { id: "3_320", english: "suburban", hebrew: "פרברי" },
    { id: "3_321", english: "succeed", hebrew: "להצליח" },
    { id: "3_322", english: "success", hebrew: "הצלחה" },
    { id: "3_323", english: "sum", hebrew: "סכום / סך הכל / לסכם" },
    { id: "3_324", english: "sum up", hebrew: "לסכם" },
    { id: "3_325", english: "summarize", hebrew: "לתמצט / לסכם" },
    { id: "3_326", english: "summary", hebrew: "סיכום / תמצית" },
    { id: "3_327", english: "surround", hebrew: "להקיף / לכתר" },
    { id: "3_328", english: "surrounding", hebrew: "סביבה / מסביב" },
    { id: "3_329", english: "task", hebrew: "משימה / מטלה" },
    { id: "3_330", english: "territory", hebrew: "טריטוריה / שטח" },
    { id: "3_331", english: "thereby", hebrew: "ובכך / כתוצאה מכך" },
    { id: "3_332", english: "title", hebrew: "כותרת / תואר" },
    { id: "3_333", english: "touch", hebrew: "לגעת / מגע / קשר" },
    { id: "3_334", english: "trade", hebrew: "מסחר / לסחור / להחליף" },
    { id: "3_335", english: "train", hebrew: "רכבת / לאמן / שורה" },
    { id: "3_336", english: "trial", hebrew: "משפט / ניסוי / צרות" },
    { id: "3_337", english: "turn", hebrew: "להסתובב / לפנות / תור" },
    { id: "3_338", english: "uncharted", hebrew: "לא ממופה / לא נודע" },
    { id: "3_339", english: "uniform", hebrew: "מדים / אחיד קבוע" },
    { id: "3_340", english: "unify", hebrew: "לאחד / ללכד" },
    { id: "3_341", english: "union", hebrew: "איחוד / איגוד מקצועי" },
    { id: "3_342", english: "universe", hebrew: "יקום / תבל" },
    { id: "3_343", english: "uphold", hebrew: "לתמוך / לשמור על" },
    { id: "3_344", english: "volume", hebrew: "נפח / עוצמת קול / כרך / כמות" },
    { id: "3_345", english: "war", hebrew: "מלחמה" },
    { id: "3_346", english: "warfare", hebrew: "לוחמה" },
    { id: "3_347", english: "warrior", hebrew: "לוחם" },
    { id: "3_348", english: "waste", hebrew: "פסולת / לבזבז / שממה" },
    { id: "3_349", english: "watch", hebrew: "לצפות / לשמור / שעון יד / משמרת" },
    { id: "3_350", english: "widespread", hebrew: "נפוץ / רחב ממדים" },
    { id: "3_351", english: "wild", hebrew: "פראי / בר" },
    { id: "3_352", english: "wilderness", hebrew: "אזור שממה / פרא" },
    { id: "3_353", english: "wool", hebrew: "צמר" }
  ],
"4": [
    { id: "4_1", english: "abandon", hebrew: "לנטוש / לעזוב לחלוטין" },
    { id: "4_2", english: "abduct", hebrew: "לחטוף (אדם)" },
    { id: "4_3", english: "abide", hebrew: "לציית / לשכון / לסבול" },
    { id: "4_4", english: "absence", hebrew: "היעדרות / חוסר" },
    { id: "4_5", english: "absent", hebrew: "נעדר / לא נמצא" },
    { id: "4_6", english: "absorb", hebrew: "לספוג / לקלוט" },
    { id: "4_7", english: "abundance", hebrew: "שפע / רוב" },
    { id: "4_8", english: "abuse", hebrew: "התעללות / שימוש לרעה / להתעלל" },
    { id: "4_9", english: "accumulate", hebrew: "לצבור / לאגור" },
    { id: "4_10", english: "acquire", hebrew: "לרכוש / להשיג" },
    { id: "4_11", english: "acquisition", hebrew: "רכישה / נכס" },
    { id: "4_12", english: "adopt", hebrew: "לאמץ (ילד/רעיון)" },
    { id: "4_13", english: "adventure", hebrew: "הרפתקה" },
    { id: "4_14", english: "affect", hebrew: "להשפיע על" },
    { id: "4_15", english: "affection", hebrew: "חיבה / אהבה" },
    { id: "4_16", english: "affluence", hebrew: "שפע / עושר" },
    { id: "4_17", english: "fluent", hebrew: "עשיר / בעל שפע" },
    { id: "4_18", english: "aid", hebrew: "עזרה / סיוע / לסייע" },
    { id: "4_19", english: "airborne", hebrew: "מוטס / נישא באוויר" },
    { id: "4_20", english: "airline", hebrew: "חברת תעופה" },
    { id: "4_21", english: "airplane", hebrew: "מטוס" },
    { id: "4_22", english: "alike", hebrew: "דומה / באותו אופן" },
    { id: "4_23", english: "allow", hebrew: "להרשות / לאפשר" },
    { id: "4_24", english: "ally (allies)", hebrew: "בעל ברית / בריתות" },
    { id: "4_25", english: "alter", hebrew: "לשנות / לתקן" },
    { id: "4_26", english: "alterations", hebrew: "שינויים / תיקונים" },
    { id: "4_27", english: "alternately", hebrew: "לסירוגין" },
    { id: "4_28", english: "amateur", hebrew: "חובבן / לא מקצועי" },
    { id: "4_29", english: "amend", hebrew: "לתקן / לשפר (חוק)" },
    { id: "4_30", english: "analyze", hebrew: "לנתח (נתונים/מצב)" },
    { id: "4_31", english: "anticipate", hebrew: "לצפות מראש" },
    { id: "4_32", english: "anxious", hebrew: "חרד / להוט משתוקק" },
    { id: "4_33", english: "apparent", hebrew: "גלוי לעין / לכאורה" },
    { id: "4_34", english: "apparently", hebrew: "ככל הנראה" },
    { id: "4_35", english: "apply", hebrew: "ליישם / להחיל / להגיש מועמדות" },
    { id: "4_36", english: "appreciate", hebrew: "להעריך / להוקיר" },
    { id: "4_37", english: "appreciation", hebrew: "הערכה / הוקרה" },
    { id: "4_38", english: "appropriately", hebrew: "כראוי / בהתאם" },
    { id: "4_39", english: "arise", hebrew: "להתעורר / לנבוע מ-" },
    { id: "4_40", english: "arise, arose", hebrew: "קם / נוצר (עבר: arose)" },
    { id: "4_41", english: "artificial", hebrew: "מלאכותי" },
    { id: "4_42", english: "aside", hebrew: "הצידה / מלבד (aside from)" },
    { id: "4_43", english: "assess", hebrew: "להעריך (שווי/נזק)" },
    { id: "4_44", english: "asset", hebrew: "נכס / קניין" },
    { id: "4_45", english: "assign", hebrew: "להקצות / להטיל משימה" },
    { id: "4_46", english: "assignment", hebrew: "משימה / מטלה" },
    { id: "4_47", english: "attain", hebrew: "להשיג / להגיע ל-" },
    { id: "4_48", english: "attend", hebrew: "נוכח / להשתתף / לטפל ב-" },
    { id: "4_49", english: "attendant", hebrew: "מלווה / סדרן / דייל" },
    { id: "4_50", english: "authority", hebrew: "סמכות / רשות" },
    { id: "4_51", english: "authorize", hebrew: "להסמיך / לאשר" },
    { id: "4_52", english: "autumn", hebrew: "סתיו" },
    { id: "4_53", english: "await", hebrew: "לחכות ל- / לצפות" },
    { id: "4_54", english: "awareness", hebrew: "מודעות" },
    { id: "4_55", english: "bare", hebrew: "חשוף / עירום / פשוט" },
    { id: "4_56", english: "behave", hebrew: "להתנהג" },
    { id: "4_57", english: "behavior", hebrew: "התנהגות" },
    { id: "4_58", english: "bounce", hebrew: "לקפץ / לחזור / החזרה" },
    { id: "4_59", english: "brilliant", hebrew: "מבריק / גאוני" },
    { id: "4_60", english: "burden", hebrew: "נטל / משא / להעמיס" },
    { id: "4_61", english: "bush", hebrew: "שיח / סבך" },
    { id: "4_62", english: "cable", hebrew: "כבל / מברק" },
    { id: "4_63", english: "calculate", hebrew: "לחשב" },
    { id: "4_64", english: "calculator", hebrew: "מחשבון" },
    { id: "4_65", english: "campaign", hebrew: "קמפיין / מערכה" },
    { id: "4_66", english: "candid", hebrew: "גלוי לב / ישר / כנה" },
    { id: "4_67", english: "candidate", hebrew: "מועמד" },
    { id: "4_68", english: "case", hebrew: "מקרה / תיק / קופסה נרתיק" },
    { id: "4_69", english: "categorize", hebrew: "לסווג לקטגוריות" },
    { id: "4_70", english: "cautious", hebrew: "זהיר" },
    { id: "4_71", english: "century", hebrew: "מאה (100 שנה)" },
    { id: "4_72", english: "charge", hebrew: "מחיר / לטעון / להאשים / פיקוח אחריות / להסתער / מטען" },
    { id: "4_73", english: "chart", hebrew: "תעודה / מפה / תרשים" },
    { id: "4_74", english: "claim", hebrew: "טענה / לטעון / תביעה / לדרוש בעלות" },
    { id: "4_75", english: "coincide", hebrew: "להתלכד / להתרחש באותו זמן" },
    { id: "4_76", english: "colossal", hebrew: "עצום / כביר" },
    { id: "4_77", english: "commence", hebrew: "להתחיל" },
    { id: "4_78", english: "compress", hebrew: "לדחוס / לכווץ" },
    { id: "4_79", english: "comprise", hebrew: "להכיל / לכלול" },
    { id: "4_80", english: "concept", hebrew: "מושג / קונספט" },
    { id: "4_81", english: "conception", hebrew: "תפיסה / מושג / התעברות" },
    { id: "4_82", english: "confer", hebrew: "להעניק / להתייעץ" },
    { id: "4_83", english: "conference", hebrew: "ועידה / כנס" },
    { id: "4_84", english: "confide", hebrew: "לספר בסוד / לבטוח" },
    { id: "4_85", english: "confident", hebrew: "בטוח בעצמו" },
    { id: "4_86", english: "conflict", hebrew: "עימות / סכסוך / להתנגש" },
    { id: "4_87", english: "conjecture", hebrew: "השערה / לנחש" },
    { id: "4_88", english: "connect", hebrew: "לחבר / לקשר" },
    { id: "4_89", english: "consequence", hebrew: "תוצאה / השלכה" },
    { id: "4_90", english: "consider", hebrew: "לשקול / להתחשב / להחשיב" },
    { id: "4_91", english: "considerable", hebrew: "ניכר / משמעותי" },
    { id: "4_92", english: "consume", hebrew: "לצרוך / לעכל / לכלות" },
    { id: "4_93", english: "consumers", hebrew: "צרכנים" },
    { id: "4_94", english: "contain", hebrew: "להכיל / לכלול" },
    { id: "4_95", english: "contemporary", hebrew: "בן זמננו / עכשווי" },
    { id: "4_96", english: "convenient", hebrew: "נוח" },
    { id: "4_97", english: "conveniently", hebrew: "בנוחות" },
    { id: "4_98", english: "convention", hebrew: "מוסכמה / ועידה / אמנה" },
    { id: "4_99", english: "conventional", hebrew: "קונבנציונלי / שגרתי" },
    { id: "4_100", english: "convert", hebrew: "להמיר / לשנות / להמיר דת" },
    { id: "4_101", english: "convey", hebrew: "להעביר (מסר/מטען)" },
    { id: "4_102", english: "courageous", hebrew: "אמיץ / נועז" },
    { id: "4_103", english: "create", hebrew: "ליצור" },
    { id: "4_104", english: "creator", hebrew: "יוצר / בורא" },
    { id: "4_105", english: "creature", hebrew: "יצור / בריאה" },
    { id: "4_106", english: "currency", hebrew: "מטבע" },
    { id: "4_107", english: "custom", hebrew: "מנהג / מכס (customs)" },
    { id: "4_108", english: "customer", hebrew: "לקוח" },
    { id: "4_109", english: "customize", hebrew: "להתאים אישית" },
    { id: "4_110", english: "damage", hebrew: "נזק / להזיק" },
    { id: "4_111", english: "decade", hebrew: "עשור (10 שנים)" },
    { id: "4_112", english: "defeat", hebrew: "תבוסה / להביס" },
    { id: "4_113", english: "defeated", hebrew: "מובס / מיואש" },
    { id: "4_114", english: "defend", hebrew: "להגן על" },
    { id: "4_115", english: "defense", hebrew: "הגנה / סנגוריה" },
    { id: "4_116", english: "deficiency", hebrew: "מחסור / ליקוי" },
    { id: "4_117", english: "deliver", hebrew: "למסור / להוביל משלוח / ליילד" },
    { id: "4_118", english: "delivery", hebrew: "משלוח / לידה" },
    { id: "4_119", english: "demographic", hebrew: "דמוגרפי" },
    { id: "4_120", english: "demonstrate", hebrew: "להדגים / להוכיח / להפגני" },
    { id: "4_121", english: "destination", hebrew: "יעד" },
    { id: "4_122", english: "detach", hebrew: "לנתק / להפריד" },
    { id: "4_123", english: "deteriorate", hebrew: "להידרדר / להחמיר" },
    { id: "4_124", english: "diagnose", hebrew: "לאבחן" },
    { id: "4_125", english: "director", hebrew: "מנהל / במאי / חבר דירקטוריון" },
    { id: "4_126", english: "discriminate", hebrew: "להפלות / להבחין בין" },
    { id: "4_127", english: "dismiss", hebrew: "לפטר / לפזר / לבטל" },
    { id: "4_128", english: "disposable", hebrew: "חד-פעמי / זמין לשימוש" },
    { id: "4_129", english: "disrupt", hebrew: "לשבש / להפריע" },
    { id: "4_130", english: "distribute", hebrew: "לחלק / להפיץ" },
    { id: "4_131", english: "distribution", hebrew: "הפצה / חלוקה" },
    { id: "4_132", english: "document", hebrew: "מסמך / לתעד" },
    { id: "4_133", english: "duty", hebrew: "חובה / תפקיד / מכס" },
    { id: "4_134", english: "earn", hebrew: "להרוויח בזכות / להשתכר" },
    { id: "4_135", english: "economy", hebrew: "כלכלה / חיסכון" },
    { id: "4_136", english: "edge", hebrew: "קצה / להב / יתרון" },
    { id: "4_137", english: "elaborate", hebrew: "להרחיב / לפרט / מורכב" },
    { id: "4_138", english: "elect", hebrew: "לבחור / נבחר" },
    { id: "4_139", english: "emerge", hebrew: "להגיח / להתגלות" },
    { id: "4_140", english: "emigrate", hebrew: "להגר החוצה" },
    { id: "4_141", english: "eminent", hebrew: "דגול / בולט" },
    { id: "4_142", english: "enclose", hebrew: "לצרף / להקיף" },
    { id: "4_143", english: "enlarge", hebrew: "להגדיל / להרחיב" },
    { id: "4_144", english: "ensure", hebrew: "להבטיח / לוודא" },
    { id: "4_145", english: "environment", hebrew: "סביבה" },
    { id: "4_146", english: "epidemic", hebrew: "מגיפה" },
    { id: "4_147", english: "equivalent", hebrew: "שווה ערך / מקביל" },
    { id: "4_148", english: "erase", hebrew: "למחוק" },
    { id: "4_149", english: "eraser", hebrew: "מחק" },
    { id: "4_150", english: "establish", hebrew: "להקים / לייסד / לבסס" },
    { id: "4_151", english: "estimate", hebrew: "הערכה / להעריך" },
    { id: "4_152", english: "ethical", hebrew: "אתי / מוסרי" },
    { id: "4_153", english: "evade", hebrew: "להתחמק / להשתמט" },
    { id: "4_154", english: "evidence", hebrew: "ראיות / עדות" },
    { id: "4_155", english: "exception", hebrew: "חריג / יוצא מן הכלל" },
    { id: "4_156", english: "execute", hebrew: "להוציא לפועל / להוציא להורג" },
    { id: "4_157", english: "facility", hebrew: "מתקן / מבנה / מיומנות" },
    { id: "4_158", english: "fail", hebrew: "להיכשל" },
    { id: "4_159", english: "failure", hebrew: "כישלון" },
    { id: "4_160", english: "faith", hebrew: "אמונה / נאמנות" },
    { id: "4_161", english: "fall", hebrew: "ליפול / נפילה / סתיו" },
    { id: "4_162", english: "feature", hebrew: "מאפיין / טור קבוע / להציג כפיצ'ר" },
    { id: "4_163", english: "flourish", hebrew: "לשגשג / לפרוח" },
    { id: "4_164", english: "follow", hebrew: "לעקוב / לבוא אחרי / לציית" },
    { id: "4_165", english: "for the sake of", hebrew: "למען / בשביל" },
    { id: "4_166", english: "force", hebrew: "כוח / לאלץ" },
    { id: "4_167", english: "forsake", hebrew: "לנטוש / לעזוב לחלוטין" },
    { id: "4_168", english: "found", hebrew: "מצא / לייסד להקים" },
    { id: "4_169", english: "foundation", hebrew: "יסוד / קרן / בסיס" },
    { id: "4_170", english: "function", hebrew: "תפקוד / פונקציה" },
    { id: "4_171", english: "future", hebrew: "עתיד" },
    { id: "4_172", english: "gather", hebrew: "לאסוף / לקבץ / להבין" },
    { id: "4_173", english: "global", hebrew: "עולמי / גלובלי" },
    { id: "4_174", english: "goal", hebrew: "מטרה / יעד" },
    { id: "4_175", english: "goods", hebrew: "סחורות" },
    { id: "4_176", english: "grasp", hebrew: "לתפוס לאחוז / תפיסה הבנה" },
    { id: "4_177", english: "group", hebrew: "קבוצה / לקבץ" },
    { id: "4_178", english: "hardly", hebrew: "בקושי / כמעט שלא" },
    { id: "4_179", english: "hesitate", hebrew: "להסס" },
    { id: "4_180", english: "hold back", hebrew: "לעצור / לרסן / לעכב" },
    { id: "4_181", english: "homeland", hebrew: "מולדת" },
    { id: "4_182", english: "honest", hebrew: "ישר / כנה" },
    { id: "4_183", english: "honor", hebrew: "כבוד / לכבד" },
    { id: "4_184", english: "huge", hebrew: "עצום / ענק" },
    { id: "4_185", english: "idea", hebrew: "רעיון / מושג" },
    { id: "4_186", english: "identify", hebrew: "לזהות / להזדהות" },
    { id: "4_187", english: "illegal", hebrew: "בלתי חוקי" },
    { id: "4_188", english: "image", hebrew: "תמונה / בבואה / תדמית" },
    { id: "4_189", english: "imagination", hebrew: "דמיון" },
    { id: "4_190", english: "imagine", hebrew: "לדמיין / לשער" },
    { id: "4_191", english: "impair", hebrew: "לפגום / להחליש" },
    { id: "4_192", english: "impart", hebrew: "להעניק / להקנות" },
    { id: "4_193", english: "impartially", hebrew: "ללא משוא פנים" },
    { id: "4_194", english: "import", hebrew: "יבוא / לייבא / חשיבות" },
    { id: "4_195", english: "impose", hebrew: "לכפות / להטיל מס" },
    { id: "4_196", english: "impossible", hebrew: "בלתי אפשרי" },
    { id: "4_197", english: "imprisoned", hebrew: "כלוא / אסור" },
    { id: "4_198", english: "improve", hebrew: "לשפר / להשתפר" },
    { id: "4_199", english: "improvise", hebrew: "לאלתר" },
    { id: "4_200", english: "in order", hebrew: "תקין / סדר / כדי ל- (in order to)" },
    { id: "4_201", english: "increase", hebrew: "להגדיל / הגדלה / עלייה" },
    { id: "4_202", english: "incredible", hebrew: "לא יאומן / מדהים" },
    { id: "4_203", english: "individual", hebrew: "פרט / אינדיבידואל" },
    { id: "4_204", english: "industry", hebrew: "תעשייה / חרוצות" },
    { id: "4_205", english: "inferred", hebrew: "הסיק / מוסק" },
    { id: "4_206", english: "inform", hebrew: "ליידע / לעדכן" },
    { id: "4_207", english: "information", hebrew: "מידע" },
    { id: "4_208", english: "innovate", hebrew: "לחדש / להמציא" },
    { id: "4_209", english: "intention", hebrew: "כוונה" },
    { id: "4_210", english: "intentional", hebrew: "מכוון / בזדון" },
    { id: "4_211", english: "interact", hebrew: "לתקשר / להשפיע זה על זה" },
    { id: "4_212", english: "interest", hebrew: "עניין / ריבית / אינטרס טובת" },
    { id: "4_213", english: "internal", hebrew: "פנימי" },
    { id: "4_214", english: "interpretation", hebrew: "פרשנות / פירוש" },
    { id: "4_215", english: "involve", hebrew: "לערב / לכלול" },
    { id: "4_216", english: "isolate", hebrew: "לבודד" },
    { id: "4_217", english: "judgment", hebrew: "שיפוט / פסק דין" },
    { id: "4_218", english: "know, knew", hebrew: "לדעת (knew/known)" },
    { id: "4_219", english: "knowledge", hebrew: "ידע" },
    { id: "4_220", english: "known", hebrew: "ידוע / מוכר" },
    { id: "4_221", english: "laid", hebrew: "הניח / הטיל (עבר של lay)" },
    { id: "4_222", english: "lane", hebrew: "נתיב / סמטה" },
    { id: "4_223", english: "launch", hebrew: "להשיק / לשגר / השקה / סירת מנוע" },
    { id: "4_224", english: "limit", hebrew: "גבול / להגביל / מגבלה" },
    { id: "4_225", english: "limitation", hebrew: "מגבלה" },
    { id: "4_226", english: "lobby", hebrew: "מבואה / לובי / ללחוץ לקדם אינטרסים" },
    { id: "4_227", english: "mammal", hebrew: "יונק" },
    { id: "4_228", english: "moderate", hebrew: "מתון / למתן / להנחות דיון" },
    { id: "4_229", english: "modernize", hebrew: "לחדש / להפוך למודרני" },
    { id: "4_230", english: "mold", hebrew: "עובש / תבנית / לעצב בתבנית" },
    { id: "4_231", english: "motivate", hebrew: "להניע / לעורר מוטיבציה" },
    { id: "4_232", english: "negate", hebrew: "לשלול / לבטל" },
    { id: "4_233", english: "neutral", hebrew: "ניטרלי" },
    { id: "4_234", english: "numerous", hebrew: "רבים / מספר גדול של" },
    { id: "4_235", english: "nutrition", hebrew: "תזונה" },
    { id: "4_236", english: "object", hebrew: "חפץ עצם מטרה / להתנגד" },
    { id: "4_237", english: "obtain", hebrew: "להשיג / לקבל" },
    { id: "4_238", english: "operate", hebrew: "להפעיל / לנתח רפואית" },
    { id: "4_239", english: "operation", hebrew: "פעולה מבצע / ניתוח" },
    { id: "4_240", english: "opposition", hebrew: "התנגדות / אופוזיציה" },
    { id: "4_241", english: "ordinary", hebrew: "רגיל / פשוט / שגרתי" },
    { id: "4_242", english: "organ", hebrew: "איבר בגוף / עוגב" },
    { id: "4_243", english: "organization", hebrew: "ארגון" },
    { id: "4_244", english: "organize", hebrew: "לארגן / לסדר" },
    { id: "4_245", english: "outbreak", hebrew: "התפרצות מחלה" },
    { id: "4_246", english: "overdo", hebrew: "להגזים / לעשות יותר מדי" },
    { id: "4_247", english: "overdue", hebrew: "באיחור / שעבר זמנו" },
    { id: "4_248", english: "pace", hebrew: "קצב / פסיעה" },
    { id: "4_249", english: "pair", hebrew: "זוג / לצמד" },
    { id: "4_250", english: "parent", hebrew: "הורה" },
    { id: "4_251", english: "parenting", hebrew: "הורות / גידול ילדים" },
    { id: "4_252", english: "participate", hebrew: "להשתתף ב-" },
    { id: "4_253", english: "particular", hebrew: "מסוים / ספציפי / קפדן" },
    { id: "4_254", english: "particulars", hebrew: "פרטים מלאים" },
    { id: "4_255", english: "pause", hebrew: "הפסקה / לעצור זמנית" },
    { id: "4_256", english: "persist", hebrew: "להתמיד / להתעקש" },
    { id: "4_257", english: "person", hebrew: "אדם / אישיות" },
    { id: "4_258", english: "personal", hebrew: "אישי / פרטי" },
    { id: "4_259", english: "personality", hebrew: "אישיות / אופי" },
    { id: "4_260", english: "phase", hebrew: "שלב / פאזה / תקופה" },
    { id: "4_261", english: "phenomenon", hebrew: "תופעה" },
    { id: "4_262", english: "pioneer", hebrew: "חלוץ / ראשון בתחום" },
    { id: "4_263", english: "position", hebrew: "עמדה תנוחה תפקיד / מיקום / דעה תפיסה" },
    { id: "4_264", english: "possible", hebrew: "אפשרי" },
    { id: "4_265", english: "poverty", hebrew: "עוני" },
    { id: "4_266", english: "poverty-stricken", hebrew: "מוכה עוני / עני מרוד" },
    { id: "4_267", english: "precedent", hebrew: "תקדים" },
    { id: "4_268", english: "preceding", hebrew: "הקודם / שבא לפני" },
    { id: "4_269", english: "predecessors", hebrew: "קודמים בתפקיד / אבות" },
    { id: "4_270", english: "predestined", hebrew: "נקבע מראש" },
    { id: "4_271", english: "predict", hebrew: "לחזות / לנבא" },
    { id: "4_272", english: "prediction", hebrew: "תחזית / ניבוי" },
    { id: "4_273", english: "predictive", hebrew: "חיזוי / בעל יכולת ניבוי" },
    { id: "4_274", english: "premature", hebrew: "לפני הזמן / פג" },
    { id: "4_275", english: "private", hebrew: "פרטי / טוראי" },
    { id: "4_276", english: "produce", hebrew: "לייצר / להפיק / תוצרת חקלאית" },
    { id: "4_277", english: "product", hebrew: "מוצר / תוצר" },
    { id: "4_278", english: "profession", hebrew: "מקצוע" },
    { id: "4_279", english: "professional", hebrew: "מקצועי" },
    { id: "4_280", english: "profound", hebrew: "עמוק / מעמיק / מוחלט נחרץ" },
    { id: "4_281", english: "profoundly", hebrew: "עמוקות / בצורה מוחלטת" },
    { id: "4_282", english: "promise", hebrew: "הבטחה / להבטיח" },
    { id: "4_283", english: "property", hebrew: "רכוש נכס / תכונה מאפיין" },
    { id: "4_284", english: "protest", hebrew: "מחאה / למחות" },
    { id: "4_285", english: "prove", hebrew: "להוכיח / להתברר כ-" },
    { id: "4_286", english: "public", hebrew: "ציבור / ציבורי / פומבי" },
    { id: "4_287", english: "race", hebrew: "מרוץ / לרוץ מהר / גזע מוצא" },
    { id: "4_288", english: "rail", hebrew: "מעקה / מסילה" },
    { id: "4_289", english: "railroad", hebrew: "מסילת רכבת" },
    { id: "4_290", english: "random", hebrew: "אקראי" },
    { id: "4_291", english: "randomly", hebrew: "באופן אקראי" },
    { id: "4_292", english: "reaction", hebrew: "תגובה / ריאקציה" },
    { id: "4_293", english: "reasonable", hebrew: "סביר / הגיוני" },
    { id: "4_294", english: "reconstruct", hebrew: "לשחזר / לבנות מחדש" },
    { id: "4_295", english: "refute", hebrew: "להפריך / לסתור" },
    { id: "4_296", english: "regain", hebrew: "להשיג בחזרה" },
    { id: "4_297", english: "regard", hebrew: "להביט / להחשיב / כבוד" },
    { id: "4_298", english: "relate", hebrew: "לקשר / להתייחס / לספר" },
    { id: "4_299", english: "release", hebrew: "לשחרר / שחרור / פרסום" },
    { id: "4_300", english: "relevant", hebrew: "רלוונטי" },
    { id: "4_301", english: "relocate", hebrew: "לשנות מיקום / לעבור" },
    { id: "4_302", english: "reluctant", hebrew: "מסתייג / לא שש" },
    { id: "4_303", english: "rely", hebrew: "להסתמך על / לבטוח" },
    { id: "4_304", english: "remote", hebrew: "רחוק / מבודד / שלט רחוק" },
    { id: "4_305", english: "report", hebrew: "דיווח / דוח / לדווח" },
    { id: "4_306", english: "reporter", hebrew: "כתב / עיתונאי" },
    { id: "4_307", english: "request", hebrew: "בקשה / לבקש" },
    { id: "4_308", english: "require", hebrew: "לדרוש / להצריך" },
    { id: "4_309", english: "restore", hebrew: "לשחזר / להחליף מצב" },
    { id: "4_310", english: "resume", hebrew: "לחדש / להמשיך" },
    { id: "4_311", english: "resumption", hebrew: "חידוש / המשך" },
    { id: "4_312", english: "rule", hebrew: "חוק כלל לשלוט / פסק דין" },
    { id: "4_313", english: "ruler", hebrew: "סרגל / שליט" },
    { id: "4_314", english: "season", hebrew: "עונה / לתבל / להרגיל" },
    { id: "4_315", english: "secure", hebrew: "מאובטח / להבטיח / להשיג" },
    { id: "4_316", english: "selective", hebrew: "סלקטיבי / בררני" },
    { id: "4_317", english: "service", hebrew: "שירות / לשרת" },
    { id: "4_318", english: "share", hebrew: "לחלוק / שותף / מניה / נתח" },
    { id: "4_319", english: "ship", hebrew: "אונייה / לשלוח סחורה" },
    { id: "4_320", english: "shipment", hebrew: "משלוח / מטען" },
    { id: "4_321", english: "significance", hebrew: "חשיבות / משמעות" },
    { id: "4_322", english: "significant", hebrew: "משמעותי / חשוב" },
    { id: "4_323", english: "simulate", hebrew: "לדמות / לעשות סימולציה" },
    { id: "4_324", english: "size", hebrew: "גודל / לדרג לפי גודל" },
    { id: "4_325", english: "soar", hebrew: "לנסוק / להמריא פלאים" },
    { id: "4_326", english: "soil", hebrew: "אדמה / ללכלך" },
    { id: "4_327", english: "solicit", hebrew: "לשדל / להפציר / לפתות" },
    { id: "4_328", english: "solitude", hebrew: "בדידות (מבחירה)" },
    { id: "4_329", english: "solution", hebrew: "פתרון / תמיסה" },
    { id: "4_330", english: "sort", hebrew: "סוג / למיין" },
    { id: "4_331", english: "source", hebrew: "מקור" },
    { id: "4_332", english: "span", hebrew: "משך / מרווח / טווח" },
    { id: "4_333", english: "splendid", hebrew: "מצוין / מפואר" },
    { id: "4_334", english: "spring", hebrew: "קפיץ / מעיין / אביב / לקפוץ" },
    { id: "4_335", english: "spring, sprang", hebrew: "נבע / זינק (sprang)" },
    { id: "4_336", english: "stability", hebrew: "יציבות" },
    { id: "4_337", english: "stamina", hebrew: "כוח עמידה / סיבולת" },
    { id: "4_338", english: "standard", hebrew: "תקן / סטנדרט" },
    { id: "4_339", english: "state", hebrew: "מדינה / מצב / להצהיר לנסח" },
    { id: "4_340", english: "statement", hebrew: "הצהרה / טענה / תדפיס" },
    { id: "4_341", english: "steady", hebrew: "יציב / קבוע" },
    { id: "4_342", english: "stimulate", hebrew: "לגרות / לעורר / לתמרץ" },
    { id: "4_343", english: "stock", hebrew: "מלאי / מניות / ציר מרק" },
    { id: "4_344", english: "strange", hebrew: "מוזר / זר" },
    { id: "4_345", english: "strive", hebrew: "לשאוף / לחתור בתוקף" },
    { id: "4_346", english: "successor", hebrew: "יורש / ממשיך דרך" },
    { id: "4_347", english: "summer", hebrew: "קיץ" },
    { id: "4_348", english: "superior", hebrew: "עליון / נעלה / מנהל ישיר" },
    { id: "4_349", english: "supervise", hebrew: "לפקח / להשגיח" },
    { id: "4_350", english: "support", hebrew: "תמיכה / לתמוך / לכלכל" },
    { id: "4_351", english: "supportive", hebrew: "תומך" },
    { id: "4_352", english: "survey", hebrew: "סקר / לסקור / מדידת שטח" },
    { id: "4_353", english: "survive", hebrew: "לשרוד" },
    { id: "4_354", english: "swift", hebrew: "מהיר / זריז" },
    { id: "4_355", english: "temporary", hebrew: "זמני" },
    { id: "4_356", english: "thick", hebrew: "עבה / סמיך / צפוף" },
    { id: "4_357", english: "thrive", hebrew: "לשגשג / להצליח" },
    { id: "4_358", english: "tradition", hebrew: "מסורת" },
    { id: "4_359", english: "traffic", hebrew: "תנועה בכביש / סחר לא חוקי" },
    { id: "4_360", english: "traffic jam", hebrew: "פקק תנועה" },
    { id: "4_361", english: "transfer", hebrew: "העברה / להעביר / כרטיס מעבר" },
    { id: "4_362", english: "tribe", hebrew: "שבט" },
    { id: "4_363", english: "unaware", hebrew: "לא מודע ל-" },
    { id: "4_364", english: "uncertain", hebrew: "לא בטוח / מוטל בספק" },
    { id: "4_365", english: "unclear", hebrew: "לא ברור" },
    { id: "4_366", english: "uncover", hebrew: "לחשוף / לגלות" },
    { id: "4_367", english: "unfold", hebrew: "לפרוש / לפתח / להתגלות" },
    { id: "4_368", english: "unit", hebrew: "יחידה / תא" },
    { id: "4_369", english: "unstable", hebrew: "לא יציב" },
    { id: "4_370", english: "update", hebrew: "עדכון / לעדכן" },
    { id: "4_371", english: "upgrade", hebrew: "שדרוג / לשדרג" },
    { id: "4_372", english: "valid", hebrew: "תקף / חוקי / הגיוני" },
    { id: "4_373", english: "validate", hebrew: "לתת תוקף / לאשר" },
    { id: "4_374", english: "violence", hebrew: "אלימות" },
    { id: "4_375", english: "violent", hebrew: "אלים" },
    { id: "4_376", english: "widely", hebrew: "במידה רבה / באופן נרחב" },
    { id: "4_377", english: "widen", hebrew: "להרחיב" },
    { id: "4_378", english: "winter", hebrew: "חורף" }
  ],
};